//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SARLAFTServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaClinton", Namespace="http://schemas.datacontract.org/2004/07/Vetos.Entidades")]
    public partial class ListaClinton : object
    {
        
        private int CodigoClienteVetadoField;
        
        private int CodigoTipoVetoField;
        
        private System.DateTime FechaHabilitaField;
        
        private System.DateTime FechaIngresoField;
        
        private System.DateTime FechaInhabilitaField;
        
        private string NombreField;
        
        private string NumeroDocumentoField;
        
        private string ObservacionesField;
        
        private int TipoDocumentoField;
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoClienteVetado
        {
            get
            {
                return this.CodigoClienteVetadoField;
            }
            set
            {
                this.CodigoClienteVetadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoTipoVeto
        {
            get
            {
                return this.CodigoTipoVetoField;
            }
            set
            {
                this.CodigoTipoVetoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaHabilita
        {
            get
            {
                return this.FechaHabilitaField;
            }
            set
            {
                this.FechaHabilitaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaIngreso
        {
            get
            {
                return this.FechaIngresoField;
            }
            set
            {
                this.FechaIngresoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaInhabilita
        {
            get
            {
                return this.FechaInhabilitaField;
            }
            set
            {
                this.FechaInhabilitaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumento
        {
            get
            {
                return this.NumeroDocumentoField;
            }
            set
            {
                this.NumeroDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones
        {
            get
            {
                return this.ObservacionesField;
            }
            set
            {
                this.ObservacionesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoDocumento
        {
            get
            {
                return this.TipoDocumentoField;
            }
            set
            {
                this.TipoDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaCartera", Namespace="http://schemas.datacontract.org/2004/07/Vetos.Entidades")]
    public partial class ListaCartera : object
    {
        
        private int CodigoClaseVetoField;
        
        private int CodigoGrupoEndosoField;
        
        private int CodigoVetoField;
        
        private string DescripcionClaseVetoField;
        
        private string DescripcionGrupoEndosoField;
        
        private string DescripcionVetoField;
        
        private System.DateTime FechaBajaVetoField;
        
        private System.DateTime FechaVetoField;
        
        private string MensajeVetoField;
        
        private string NombreField;
        
        private string NumeroDocumentoField;
        
        private int TipoDocumentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoClaseVeto
        {
            get
            {
                return this.CodigoClaseVetoField;
            }
            set
            {
                this.CodigoClaseVetoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoGrupoEndoso
        {
            get
            {
                return this.CodigoGrupoEndosoField;
            }
            set
            {
                this.CodigoGrupoEndosoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoVeto
        {
            get
            {
                return this.CodigoVetoField;
            }
            set
            {
                this.CodigoVetoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionClaseVeto
        {
            get
            {
                return this.DescripcionClaseVetoField;
            }
            set
            {
                this.DescripcionClaseVetoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionGrupoEndoso
        {
            get
            {
                return this.DescripcionGrupoEndosoField;
            }
            set
            {
                this.DescripcionGrupoEndosoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionVeto
        {
            get
            {
                return this.DescripcionVetoField;
            }
            set
            {
                this.DescripcionVetoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaBajaVeto
        {
            get
            {
                return this.FechaBajaVetoField;
            }
            set
            {
                this.FechaBajaVetoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaVeto
        {
            get
            {
                return this.FechaVetoField;
            }
            set
            {
                this.FechaVetoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeVeto
        {
            get
            {
                return this.MensajeVetoField;
            }
            set
            {
                this.MensajeVetoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumento
        {
            get
            {
                return this.NumeroDocumentoField;
            }
            set
            {
                this.NumeroDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoDocumento
        {
            get
            {
                return this.TipoDocumentoField;
            }
            set
            {
                this.TipoDocumentoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaPlaca", Namespace="http://schemas.datacontract.org/2004/07/Vetos.Entidades")]
    public partial class ListaPlaca : object
    {
        
        private string FechaIngresoField;
        
        private string MotorField;
        
        private string NombreUsuarioField;
        
        private string PlacaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaIngreso
        {
            get
            {
                return this.FechaIngresoField;
            }
            set
            {
                this.FechaIngresoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Motor
        {
            get
            {
                return this.MotorField;
            }
            set
            {
                this.MotorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario
        {
            get
            {
                return this.NombreUsuarioField;
            }
            set
            {
                this.NombreUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Placa
        {
            get
            {
                return this.PlacaField;
            }
            set
            {
                this.PlacaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaCsnu", Namespace="http://schemas.datacontract.org/2004/07/Vetos.Entidades")]
    public partial class ListaCsnu : object
    {
        
        private int BlVetoField;
        
        private string StrVetoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BlVeto
        {
            get
            {
                return this.BlVetoField;
            }
            set
            {
                this.BlVetoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrVeto
        {
            get
            {
                return this.StrVetoField;
            }
            set
            {
                this.StrVetoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SARLAFTServiceReference.IService")]
    public interface IService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConsultarListaClinton", ReplyAction="http://tempuri.org/IService/ConsultarListaClintonResponse")]
        System.Threading.Tasks.Task<SARLAFTServiceReference.ListaClinton[]> ConsultarListaClintonAsync(int TipoDocumento, string NumeroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConsultarListaCartera", ReplyAction="http://tempuri.org/IService/ConsultarListaCarteraResponse")]
        System.Threading.Tasks.Task<SARLAFTServiceReference.ListaCartera[]> ConsultarListaCarteraAsync(int TipoDocumento, string NumeroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConsultarListaPlaca", ReplyAction="http://tempuri.org/IService/ConsultarListaPlacaResponse")]
        System.Threading.Tasks.Task<SARLAFTServiceReference.ListaPlaca> ConsultarListaPlacaAsync(string Placa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ValidarListaCSNU", ReplyAction="http://tempuri.org/IService/ValidarListaCSNUResponse")]
        System.Threading.Tasks.Task<SARLAFTServiceReference.ListaCsnu> ValidarListaCSNUAsync(string apellido1, string apellido2, string nombre, string nombre2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IServiceChannel : SARLAFTServiceReference.IService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<SARLAFTServiceReference.IService>, SARLAFTServiceReference.IService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient() : 
                base(ServiceClient.GetDefaultBinding(), ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SARLAFTServiceReference.ListaClinton[]> ConsultarListaClintonAsync(int TipoDocumento, string NumeroDocumento)
        {
            return base.Channel.ConsultarListaClintonAsync(TipoDocumento, NumeroDocumento);
        }
        
        public System.Threading.Tasks.Task<SARLAFTServiceReference.ListaCartera[]> ConsultarListaCarteraAsync(int TipoDocumento, string NumeroDocumento)
        {
            return base.Channel.ConsultarListaCarteraAsync(TipoDocumento, NumeroDocumento);
        }
        
        public System.Threading.Tasks.Task<SARLAFTServiceReference.ListaPlaca> ConsultarListaPlacaAsync(string Placa)
        {
            return base.Channel.ConsultarListaPlacaAsync(Placa);
        }
        
        public System.Threading.Tasks.Task<SARLAFTServiceReference.ListaCsnu> ValidarListaCSNUAsync(string apellido1, string apellido2, string nombre, string nombre2)
        {
            return base.Channel.ValidarListaCSNUAsync(apellido1, apellido2, nombre, nombre2);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                return new System.ServiceModel.EndpointAddress("http://192.1.3.183:8082/WCFVetos/Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService,
        }
    }
}
