//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilidadesSolidariaServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades")]
    public interface IWCFSolidariaUtilidades
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSolidariaUtilidades/GenerarRegistroImpresionPoliza", ReplyAction="http://tempuri.org/IWCFSolidariaUtilidades/GenerarRegistroImpresionPolizaResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.GenerarRegistroImpresionPolizaResponse> GenerarRegistroImpresionPolizaAsync(UtilidadesSolidariaServiceReference.GenerarRegistroImpresionPolizaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSolidariaUtilidades/InsertarDatosPoliza", ReplyAction="http://tempuri.org/IWCFSolidariaUtilidades/InsertarDatosPolizaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.InsertarDatosPolizaResponse> InsertarDatosPolizaAsync(UtilidadesSolidariaServiceReference.InsertarDatosPolizaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSolidariaUtilidades/ObtenerPDF", ReplyAction="http://tempuri.org/IWCFSolidariaUtilidades/ObtenerPDFResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.ObtenerPDFResponse> ObtenerPDFAsync(UtilidadesSolidariaServiceReference.ObtenerPDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSolidariaUtilidades/Encripta", ReplyAction="http://tempuri.org/IWCFSolidariaUtilidades/EncriptaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.EncriptaResponse> EncriptaAsync(UtilidadesSolidariaServiceReference.EncriptaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSolidariaUtilidades/Desencripta", ReplyAction="http://tempuri.org/IWCFSolidariaUtilidades/DesencriptaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.DesencriptaResponse> DesencriptaAsync(UtilidadesSolidariaServiceReference.DesencriptaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSolidariaUtilidades/AgregaClavePDF", ReplyAction="http://tempuri.org/IWCFSolidariaUtilidades/AgregaClavePDFResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.AgregaClavePDFResponse> AgregaClavePDFAsync(UtilidadesSolidariaServiceReference.AgregaClavePDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSolidariaUtilidades/EnvioCorreo", ReplyAction="http://tempuri.org/IWCFSolidariaUtilidades/EnvioCorreoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.EnvioCorreoResponse> EnvioCorreoAsync(UtilidadesSolidariaServiceReference.EnvioCorreoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSolidariaUtilidades/GestionCorreo", ReplyAction="http://tempuri.org/IWCFSolidariaUtilidades/GestionCorreoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.GestionCorreoResponse> GestionCorreoAsync(UtilidadesSolidariaServiceReference.GestionCorreoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSolidariaUtilidades/ImprimirPolizaSise", ReplyAction="http://tempuri.org/IWCFSolidariaUtilidades/ImprimirPolizaSiseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.ImprimirPolizaSiseResponse> ImprimirPolizaSiseAsync(UtilidadesSolidariaServiceReference.ImprimirPolizaSiseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSolidariaUtilidades/ConsultaSOAT", ReplyAction="http://tempuri.org/IWCFSolidariaUtilidades/ConsultaSOATResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.ConsultaSOATResponse> ConsultaSOATAsync(UtilidadesSolidariaServiceReference.ConsultaSOATRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSolidariaUtilidades/UsuarioToken", ReplyAction="http://tempuri.org/IWCFSolidariaUtilidades/UsuarioTokenResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.UsuarioTokenResponse> UsuarioTokenAsync(UtilidadesSolidariaServiceReference.UsuarioTokenRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SolidariaUtilidades.Entidades")]
    public partial class ImpresionPoliza
    {
        
        private byte[] archivoField;
        
        private int codigoRamoField;
        
        private bool codigoRamoFieldSpecified;
        
        private int codigoSucursalField;
        
        private bool codigoSucursalFieldSpecified;
        
        private string codigoUsuarioField;
        
        private string codigoUsuarioSiseField;
        
        private int idAplicacionField;
        
        private bool idAplicacionFieldSpecified;
        
        private int idImpresionPortalAseguradoField;
        
        private bool idImpresionPortalAseguradoFieldSpecified;
        
        private string nombreImpresoraField;
        
        private int numeroEndosoField;
        
        private bool numeroEndosoFieldSpecified;
        
        private long numeroPolizaField;
        
        private bool numeroPolizaFieldSpecified;
        
        private string rutaImpresionField;
        
        private bool snEnvioCorreoField;
        
        private bool snEnvioCorreoFieldSpecified;
        
        private bool snImpresionField;
        
        private bool snImpresionFieldSpecified;
        
        private int transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=0)]
        public byte[] Archivo
        {
            get
            {
                return this.archivoField;
            }
            set
            {
                this.archivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CodigoRamo
        {
            get
            {
                return this.codigoRamoField;
            }
            set
            {
                this.codigoRamoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoRamoSpecified
        {
            get
            {
                return this.codigoRamoFieldSpecified;
            }
            set
            {
                this.codigoRamoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int CodigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoSucursalSpecified
        {
            get
            {
                return this.codigoSucursalFieldSpecified;
            }
            set
            {
                this.codigoSucursalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string CodigoUsuario
        {
            get
            {
                return this.codigoUsuarioField;
            }
            set
            {
                this.codigoUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string CodigoUsuarioSise
        {
            get
            {
                return this.codigoUsuarioSiseField;
            }
            set
            {
                this.codigoUsuarioSiseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int IdAplicacion
        {
            get
            {
                return this.idAplicacionField;
            }
            set
            {
                this.idAplicacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdAplicacionSpecified
        {
            get
            {
                return this.idAplicacionFieldSpecified;
            }
            set
            {
                this.idAplicacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int IdImpresionPortalAsegurado
        {
            get
            {
                return this.idImpresionPortalAseguradoField;
            }
            set
            {
                this.idImpresionPortalAseguradoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdImpresionPortalAseguradoSpecified
        {
            get
            {
                return this.idImpresionPortalAseguradoFieldSpecified;
            }
            set
            {
                this.idImpresionPortalAseguradoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string NombreImpresora
        {
            get
            {
                return this.nombreImpresoraField;
            }
            set
            {
                this.nombreImpresoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int NumeroEndoso
        {
            get
            {
                return this.numeroEndosoField;
            }
            set
            {
                this.numeroEndosoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumeroEndosoSpecified
        {
            get
            {
                return this.numeroEndosoFieldSpecified;
            }
            set
            {
                this.numeroEndosoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public long NumeroPoliza
        {
            get
            {
                return this.numeroPolizaField;
            }
            set
            {
                this.numeroPolizaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumeroPolizaSpecified
        {
            get
            {
                return this.numeroPolizaFieldSpecified;
            }
            set
            {
                this.numeroPolizaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string RutaImpresion
        {
            get
            {
                return this.rutaImpresionField;
            }
            set
            {
                this.rutaImpresionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool SnEnvioCorreo
        {
            get
            {
                return this.snEnvioCorreoField;
            }
            set
            {
                this.snEnvioCorreoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SnEnvioCorreoSpecified
        {
            get
            {
                return this.snEnvioCorreoFieldSpecified;
            }
            set
            {
                this.snEnvioCorreoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool SnImpresion
        {
            get
            {
                return this.snImpresionField;
            }
            set
            {
                this.snImpresionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SnImpresionSpecified
        {
            get
            {
                return this.snImpresionFieldSpecified;
            }
            set
            {
                this.snImpresionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int Transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransaccionSpecified
        {
            get
            {
                return this.transaccionFieldSpecified;
            }
            set
            {
                this.transaccionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SolidariaUtilidades.Entidades")]
    public partial class ImpresionPolizaSise
    {
        
        private short codigoRamoField;
        
        private bool codigoRamoFieldSpecified;
        
        private short codigoSucursalField;
        
        private bool codigoSucursalFieldSpecified;
        
        private string nombreImpresoraField;
        
        private string numeroDocumentoField;
        
        private int numeroEndosoField;
        
        private bool numeroEndosoFieldSpecified;
        
        private string numeroPolizaField;
        
        private short sNReimprimeField;
        
        private bool sNReimprimeFieldSpecified;
        
        private short tipoDocumentoField;
        
        private bool tipoDocumentoFieldSpecified;
        
        private string usarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public short CodigoRamo
        {
            get
            {
                return this.codigoRamoField;
            }
            set
            {
                this.codigoRamoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoRamoSpecified
        {
            get
            {
                return this.codigoRamoFieldSpecified;
            }
            set
            {
                this.codigoRamoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public short CodigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoSucursalSpecified
        {
            get
            {
                return this.codigoSucursalFieldSpecified;
            }
            set
            {
                this.codigoSucursalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string NombreImpresora
        {
            get
            {
                return this.nombreImpresoraField;
            }
            set
            {
                this.nombreImpresoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string NumeroDocumento
        {
            get
            {
                return this.numeroDocumentoField;
            }
            set
            {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int NumeroEndoso
        {
            get
            {
                return this.numeroEndosoField;
            }
            set
            {
                this.numeroEndosoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumeroEndosoSpecified
        {
            get
            {
                return this.numeroEndosoFieldSpecified;
            }
            set
            {
                this.numeroEndosoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string NumeroPoliza
        {
            get
            {
                return this.numeroPolizaField;
            }
            set
            {
                this.numeroPolizaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public short SNReimprime
        {
            get
            {
                return this.sNReimprimeField;
            }
            set
            {
                this.sNReimprimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SNReimprimeSpecified
        {
            get
            {
                return this.sNReimprimeFieldSpecified;
            }
            set
            {
                this.sNReimprimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public short TipoDocumento
        {
            get
            {
                return this.tipoDocumentoField;
            }
            set
            {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TipoDocumentoSpecified
        {
            get
            {
                return this.tipoDocumentoFieldSpecified;
            }
            set
            {
                this.tipoDocumentoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string Usario
        {
            get
            {
                return this.usarioField;
            }
            set
            {
                this.usarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SolidariaUtilidades.Entidades")]
    public partial class GestionCorreo
    {
        
        private string[] adjuntoField;
        
        private string asuntoField;
        
        private string[] ccField;
        
        private string[] cCOField;
        
        private string clavePDFField;
        
        private string claveUsuarioCorreoField;
        
        private int codigoRamoField;
        
        private bool codigoRamoFieldSpecified;
        
        private int codigoSucursalField;
        
        private bool codigoSucursalFieldSpecified;
        
        private int codigoTipoDocumentoField;
        
        private bool codigoTipoDocumentoFieldSpecified;
        
        private string codigoUsuarioField;
        
        private string deField;
        
        private string nombreImpresoraField;
        
        private string numeroDocumentoField;
        
        private int numeroEndosoField;
        
        private bool numeroEndosoFieldSpecified;
        
        private long numeroPolizaField;
        
        private bool numeroPolizaFieldSpecified;
        
        private string[] paraField;
        
        private bool sNClavePDFField;
        
        private bool sNClavePDFFieldSpecified;
        
        private bool sNCorreoHTMLField;
        
        private bool sNCorreoHTMLFieldSpecified;
        
        private bool sNEnviarCorreoField;
        
        private bool sNEnviarCorreoFieldSpecified;
        
        private bool sNEnviarSeparadoParaField;
        
        private bool sNEnviarSeparadoParaFieldSpecified;
        
        private bool sNGrabaCopiaEnviadoCorreoField;
        
        private bool sNGrabaCopiaEnviadoCorreoFieldSpecified;
        
        private bool sNImpresionField;
        
        private bool sNImpresionFieldSpecified;
        
        private bool sNServicioField;
        
        private bool sNServicioFieldSpecified;
        
        private string textoField;
        
        private string usuarioCorreoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] Adjunto
        {
            get
            {
                return this.adjuntoField;
            }
            set
            {
                this.adjuntoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Asunto
        {
            get
            {
                return this.asuntoField;
            }
            set
            {
                this.asuntoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] CC
        {
            get
            {
                return this.ccField;
            }
            set
            {
                this.ccField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] CCO
        {
            get
            {
                return this.cCOField;
            }
            set
            {
                this.cCOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string ClavePDF
        {
            get
            {
                return this.clavePDFField;
            }
            set
            {
                this.clavePDFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string ClaveUsuarioCorreo
        {
            get
            {
                return this.claveUsuarioCorreoField;
            }
            set
            {
                this.claveUsuarioCorreoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int CodigoRamo
        {
            get
            {
                return this.codigoRamoField;
            }
            set
            {
                this.codigoRamoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoRamoSpecified
        {
            get
            {
                return this.codigoRamoFieldSpecified;
            }
            set
            {
                this.codigoRamoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int CodigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoSucursalSpecified
        {
            get
            {
                return this.codigoSucursalFieldSpecified;
            }
            set
            {
                this.codigoSucursalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int CodigoTipoDocumento
        {
            get
            {
                return this.codigoTipoDocumentoField;
            }
            set
            {
                this.codigoTipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoTipoDocumentoSpecified
        {
            get
            {
                return this.codigoTipoDocumentoFieldSpecified;
            }
            set
            {
                this.codigoTipoDocumentoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string CodigoUsuario
        {
            get
            {
                return this.codigoUsuarioField;
            }
            set
            {
                this.codigoUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string De
        {
            get
            {
                return this.deField;
            }
            set
            {
                this.deField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string NombreImpresora
        {
            get
            {
                return this.nombreImpresoraField;
            }
            set
            {
                this.nombreImpresoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string NumeroDocumento
        {
            get
            {
                return this.numeroDocumentoField;
            }
            set
            {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int NumeroEndoso
        {
            get
            {
                return this.numeroEndosoField;
            }
            set
            {
                this.numeroEndosoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumeroEndosoSpecified
        {
            get
            {
                return this.numeroEndosoFieldSpecified;
            }
            set
            {
                this.numeroEndosoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public long NumeroPoliza
        {
            get
            {
                return this.numeroPolizaField;
            }
            set
            {
                this.numeroPolizaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumeroPolizaSpecified
        {
            get
            {
                return this.numeroPolizaFieldSpecified;
            }
            set
            {
                this.numeroPolizaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=15)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] Para
        {
            get
            {
                return this.paraField;
            }
            set
            {
                this.paraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool SNClavePDF
        {
            get
            {
                return this.sNClavePDFField;
            }
            set
            {
                this.sNClavePDFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SNClavePDFSpecified
        {
            get
            {
                return this.sNClavePDFFieldSpecified;
            }
            set
            {
                this.sNClavePDFFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool SNCorreoHTML
        {
            get
            {
                return this.sNCorreoHTMLField;
            }
            set
            {
                this.sNCorreoHTMLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SNCorreoHTMLSpecified
        {
            get
            {
                return this.sNCorreoHTMLFieldSpecified;
            }
            set
            {
                this.sNCorreoHTMLFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool SNEnviarCorreo
        {
            get
            {
                return this.sNEnviarCorreoField;
            }
            set
            {
                this.sNEnviarCorreoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SNEnviarCorreoSpecified
        {
            get
            {
                return this.sNEnviarCorreoFieldSpecified;
            }
            set
            {
                this.sNEnviarCorreoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public bool SNEnviarSeparadoPara
        {
            get
            {
                return this.sNEnviarSeparadoParaField;
            }
            set
            {
                this.sNEnviarSeparadoParaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SNEnviarSeparadoParaSpecified
        {
            get
            {
                return this.sNEnviarSeparadoParaFieldSpecified;
            }
            set
            {
                this.sNEnviarSeparadoParaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public bool SNGrabaCopiaEnviadoCorreo
        {
            get
            {
                return this.sNGrabaCopiaEnviadoCorreoField;
            }
            set
            {
                this.sNGrabaCopiaEnviadoCorreoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SNGrabaCopiaEnviadoCorreoSpecified
        {
            get
            {
                return this.sNGrabaCopiaEnviadoCorreoFieldSpecified;
            }
            set
            {
                this.sNGrabaCopiaEnviadoCorreoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool SNImpresion
        {
            get
            {
                return this.sNImpresionField;
            }
            set
            {
                this.sNImpresionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SNImpresionSpecified
        {
            get
            {
                return this.sNImpresionFieldSpecified;
            }
            set
            {
                this.sNImpresionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public bool SNServicio
        {
            get
            {
                return this.sNServicioField;
            }
            set
            {
                this.sNServicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SNServicioSpecified
        {
            get
            {
                return this.sNServicioFieldSpecified;
            }
            set
            {
                this.sNServicioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string Texto
        {
            get
            {
                return this.textoField;
            }
            set
            {
                this.textoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public string UsuarioCorreo
        {
            get
            {
                return this.usuarioCorreoField;
            }
            set
            {
                this.usuarioCorreoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SolidariaUtilidades.Entidades")]
    public partial class Resultado
    {
        
        private int codigoEstadoField;
        
        private bool codigoEstadoFieldSpecified;
        
        private string descripcionEstadoField;
        
        private string rutaPDFField;
        
        private bool snErrorField;
        
        private bool snErrorFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CodigoEstado
        {
            get
            {
                return this.codigoEstadoField;
            }
            set
            {
                this.codigoEstadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoEstadoSpecified
        {
            get
            {
                return this.codigoEstadoFieldSpecified;
            }
            set
            {
                this.codigoEstadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string DescripcionEstado
        {
            get
            {
                return this.descripcionEstadoField;
            }
            set
            {
                this.descripcionEstadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string RutaPDF
        {
            get
            {
                return this.rutaPDFField;
            }
            set
            {
                this.rutaPDFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool SnError
        {
            get
            {
                return this.snErrorField;
            }
            set
            {
                this.snErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SnErrorSpecified
        {
            get
            {
                return this.snErrorFieldSpecified;
            }
            set
            {
                this.snErrorFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SolidariaUtilidades.Entidades")]
    public partial class Correo
    {
        
        private string[] adjuntoField;
        
        private string asuntoField;
        
        private string[] ccField;
        
        private string[] cCOField;
        
        private string deField;
        
        private string dominioField;
        
        private bool enableSSLField;
        
        private bool enableSSLFieldSpecified;
        
        private string hostField;
        
        private BodyType isBodyHTMLField;
        
        private bool isBodyHTMLFieldSpecified;
        
        private string[] paraField;
        
        private int puertoField;
        
        private bool puertoFieldSpecified;
        
        private string pwdField;
        
        private bool snGrabaCopiaEnviadoField;
        
        private bool snGrabaCopiaEnviadoFieldSpecified;
        
        private string textoField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] Adjunto
        {
            get
            {
                return this.adjuntoField;
            }
            set
            {
                this.adjuntoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Asunto
        {
            get
            {
                return this.asuntoField;
            }
            set
            {
                this.asuntoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] CC
        {
            get
            {
                return this.ccField;
            }
            set
            {
                this.ccField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] CCO
        {
            get
            {
                return this.cCOField;
            }
            set
            {
                this.cCOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string De
        {
            get
            {
                return this.deField;
            }
            set
            {
                this.deField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string Dominio
        {
            get
            {
                return this.dominioField;
            }
            set
            {
                this.dominioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool EnableSSL
        {
            get
            {
                return this.enableSSLField;
            }
            set
            {
                this.enableSSLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnableSSLSpecified
        {
            get
            {
                return this.enableSSLFieldSpecified;
            }
            set
            {
                this.enableSSLFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string Host
        {
            get
            {
                return this.hostField;
            }
            set
            {
                this.hostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public BodyType IsBodyHTML
        {
            get
            {
                return this.isBodyHTMLField;
            }
            set
            {
                this.isBodyHTMLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsBodyHTMLSpecified
        {
            get
            {
                return this.isBodyHTMLFieldSpecified;
            }
            set
            {
                this.isBodyHTMLFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] Para
        {
            get
            {
                return this.paraField;
            }
            set
            {
                this.paraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int Puerto
        {
            get
            {
                return this.puertoField;
            }
            set
            {
                this.puertoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PuertoSpecified
        {
            get
            {
                return this.puertoFieldSpecified;
            }
            set
            {
                this.puertoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string Pwd
        {
            get
            {
                return this.pwdField;
            }
            set
            {
                this.pwdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool SnGrabaCopiaEnviado
        {
            get
            {
                return this.snGrabaCopiaEnviadoField;
            }
            set
            {
                this.snGrabaCopiaEnviadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SnGrabaCopiaEnviadoSpecified
        {
            get
            {
                return this.snGrabaCopiaEnviadoFieldSpecified;
            }
            set
            {
                this.snGrabaCopiaEnviadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string Texto
        {
            get
            {
                return this.textoField;
            }
            set
            {
                this.textoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string Usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SolidariaUtilidades.Entidades")]
    public enum BodyType
    {
        
        /// <remarks/>
        HTML,
        
        /// <remarks/>
        Text,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SolidariaUtilidades.Entidades")]
    public partial class pwdPDF
    {
        
        private string clavePDFField;
        
        private string rutaPDFField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string ClavePDF
        {
            get
            {
                return this.clavePDFField;
            }
            set
            {
                this.clavePDFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string RutaPDF
        {
            get
            {
                return this.rutaPDFField;
            }
            set
            {
                this.rutaPDFField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SolidariaUtilidades.Entidades")]
    public partial class Herramientas
    {
        
        private string stTextoCodificaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string StTextoCodifica
        {
            get
            {
                return this.stTextoCodificaField;
            }
            set
            {
                this.stTextoCodificaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SolidariaUtilidades.Entidades")]
    public partial class InsertaDatosImpresion
    {
        
        private int codigoRamoField;
        
        private bool codigoRamoFieldSpecified;
        
        private int codigoSucursalField;
        
        private bool codigoSucursalFieldSpecified;
        
        private int codigoTipoDocumentoField;
        
        private bool codigoTipoDocumentoFieldSpecified;
        
        private string codigoUsuarioField;
        
        private string nombreImpresoraField;
        
        private string numeroDocumentoField;
        
        private int numeroEndosoField;
        
        private bool numeroEndosoFieldSpecified;
        
        private long numeroPolizaField;
        
        private bool numeroPolizaFieldSpecified;
        
        private int snImpresionField;
        
        private bool snImpresionFieldSpecified;
        
        private int transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CodigoRamo
        {
            get
            {
                return this.codigoRamoField;
            }
            set
            {
                this.codigoRamoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoRamoSpecified
        {
            get
            {
                return this.codigoRamoFieldSpecified;
            }
            set
            {
                this.codigoRamoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CodigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoSucursalSpecified
        {
            get
            {
                return this.codigoSucursalFieldSpecified;
            }
            set
            {
                this.codigoSucursalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int CodigoTipoDocumento
        {
            get
            {
                return this.codigoTipoDocumentoField;
            }
            set
            {
                this.codigoTipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoTipoDocumentoSpecified
        {
            get
            {
                return this.codigoTipoDocumentoFieldSpecified;
            }
            set
            {
                this.codigoTipoDocumentoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string CodigoUsuario
        {
            get
            {
                return this.codigoUsuarioField;
            }
            set
            {
                this.codigoUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string NombreImpresora
        {
            get
            {
                return this.nombreImpresoraField;
            }
            set
            {
                this.nombreImpresoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string NumeroDocumento
        {
            get
            {
                return this.numeroDocumentoField;
            }
            set
            {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int NumeroEndoso
        {
            get
            {
                return this.numeroEndosoField;
            }
            set
            {
                this.numeroEndosoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumeroEndosoSpecified
        {
            get
            {
                return this.numeroEndosoFieldSpecified;
            }
            set
            {
                this.numeroEndosoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long NumeroPoliza
        {
            get
            {
                return this.numeroPolizaField;
            }
            set
            {
                this.numeroPolizaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumeroPolizaSpecified
        {
            get
            {
                return this.numeroPolizaFieldSpecified;
            }
            set
            {
                this.numeroPolizaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int SnImpresion
        {
            get
            {
                return this.snImpresionField;
            }
            set
            {
                this.snImpresionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SnImpresionSpecified
        {
            get
            {
                return this.snImpresionFieldSpecified;
            }
            set
            {
                this.snImpresionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int Transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransaccionSpecified
        {
            get
            {
                return this.transaccionFieldSpecified;
            }
            set
            {
                this.transaccionFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerarRegistroImpresionPoliza", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GenerarRegistroImpresionPolizaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UtilidadesSolidariaServiceReference.ImpresionPoliza pImpresionPoliza;
        
        public GenerarRegistroImpresionPolizaRequest()
        {
        }
        
        public GenerarRegistroImpresionPolizaRequest(UtilidadesSolidariaServiceReference.ImpresionPoliza pImpresionPoliza)
        {
            this.pImpresionPoliza = pImpresionPoliza;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerarRegistroImpresionPolizaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GenerarRegistroImpresionPolizaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UtilidadesSolidariaServiceReference.ImpresionPoliza GenerarRegistroImpresionPolizaResult;
        
        public GenerarRegistroImpresionPolizaResponse()
        {
        }
        
        public GenerarRegistroImpresionPolizaResponse(UtilidadesSolidariaServiceReference.ImpresionPoliza GenerarRegistroImpresionPolizaResult)
        {
            this.GenerarRegistroImpresionPolizaResult = GenerarRegistroImpresionPolizaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertarDatosPoliza", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertarDatosPolizaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UtilidadesSolidariaServiceReference.InsertaDatosImpresion pInsertaImpresionPoliza;
        
        public InsertarDatosPolizaRequest()
        {
        }
        
        public InsertarDatosPolizaRequest(UtilidadesSolidariaServiceReference.InsertaDatosImpresion pInsertaImpresionPoliza)
        {
            this.pInsertaImpresionPoliza = pInsertaImpresionPoliza;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertarDatosPolizaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertarDatosPolizaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string InsertarDatosPolizaResult;
        
        public InsertarDatosPolizaResponse()
        {
        }
        
        public InsertarDatosPolizaResponse(string InsertarDatosPolizaResult)
        {
            this.InsertarDatosPolizaResult = InsertarDatosPolizaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerPDF", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerPDFRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RutaImpresion;
        
        public ObtenerPDFRequest()
        {
        }
        
        public ObtenerPDFRequest(string RutaImpresion)
        {
            this.RutaImpresion = RutaImpresion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerPDFResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerPDFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] ObtenerPDFResult;
        
        public ObtenerPDFResponse()
        {
        }
        
        public ObtenerPDFResponse(byte[] ObtenerPDFResult)
        {
            this.ObtenerPDFResult = ObtenerPDFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Encripta", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EncriptaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pParametro;
        
        public EncriptaRequest()
        {
        }
        
        public EncriptaRequest(string pParametro)
        {
            this.pParametro = pParametro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EncriptaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EncriptaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UtilidadesSolidariaServiceReference.Herramientas EncriptaResult;
        
        public EncriptaResponse()
        {
        }
        
        public EncriptaResponse(UtilidadesSolidariaServiceReference.Herramientas EncriptaResult)
        {
            this.EncriptaResult = EncriptaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Desencripta", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DesencriptaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pParametro;
        
        public DesencriptaRequest()
        {
        }
        
        public DesencriptaRequest(string pParametro)
        {
            this.pParametro = pParametro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DesencriptaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DesencriptaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UtilidadesSolidariaServiceReference.Herramientas DesencriptaResult;
        
        public DesencriptaResponse()
        {
        }
        
        public DesencriptaResponse(UtilidadesSolidariaServiceReference.Herramientas DesencriptaResult)
        {
            this.DesencriptaResult = DesencriptaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregaClavePDF", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AgregaClavePDFRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UtilidadesSolidariaServiceReference.pwdPDF pParametro;
        
        public AgregaClavePDFRequest()
        {
        }
        
        public AgregaClavePDFRequest(UtilidadesSolidariaServiceReference.pwdPDF pParametro)
        {
            this.pParametro = pParametro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregaClavePDFResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AgregaClavePDFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AgregaClavePDFResult;
        
        public AgregaClavePDFResponse()
        {
        }
        
        public AgregaClavePDFResponse(bool AgregaClavePDFResult)
        {
            this.AgregaClavePDFResult = AgregaClavePDFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioCorreo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EnvioCorreoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UtilidadesSolidariaServiceReference.Correo pDatosCorreo;
        
        public EnvioCorreoRequest()
        {
        }
        
        public EnvioCorreoRequest(UtilidadesSolidariaServiceReference.Correo pDatosCorreo)
        {
            this.pDatosCorreo = pDatosCorreo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioCorreoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EnvioCorreoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UtilidadesSolidariaServiceReference.Resultado EnvioCorreoResult;
        
        public EnvioCorreoResponse()
        {
        }
        
        public EnvioCorreoResponse(UtilidadesSolidariaServiceReference.Resultado EnvioCorreoResult)
        {
            this.EnvioCorreoResult = EnvioCorreoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GestionCorreo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GestionCorreoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UtilidadesSolidariaServiceReference.GestionCorreo pDatosGestionCorreo;
        
        public GestionCorreoRequest()
        {
        }
        
        public GestionCorreoRequest(UtilidadesSolidariaServiceReference.GestionCorreo pDatosGestionCorreo)
        {
            this.pDatosGestionCorreo = pDatosGestionCorreo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GestionCorreoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GestionCorreoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SolidariaUtilidades.Entidades")]
        public UtilidadesSolidariaServiceReference.Resultado[] GestionCorreoResult;
        
        public GestionCorreoResponse()
        {
        }
        
        public GestionCorreoResponse(UtilidadesSolidariaServiceReference.Resultado[] GestionCorreoResult)
        {
            this.GestionCorreoResult = GestionCorreoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImprimirPolizaSise", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ImprimirPolizaSiseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UtilidadesSolidariaServiceReference.ImpresionPolizaSise pDatosPoliza;
        
        public ImprimirPolizaSiseRequest()
        {
        }
        
        public ImprimirPolizaSiseRequest(UtilidadesSolidariaServiceReference.ImpresionPolizaSise pDatosPoliza)
        {
            this.pDatosPoliza = pDatosPoliza;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImprimirPolizaSiseResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ImprimirPolizaSiseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UtilidadesSolidariaServiceReference.Resultado ImprimirPolizaSiseResult;
        
        public ImprimirPolizaSiseResponse()
        {
        }
        
        public ImprimirPolizaSiseResponse(UtilidadesSolidariaServiceReference.Resultado ImprimirPolizaSiseResult)
        {
            this.ImprimirPolizaSiseResult = ImprimirPolizaSiseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaSOAT", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultaSOATRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int codigoSucursal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int codigoRamo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public long numeroPoliza;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int numeroEndoso;
        
        public ConsultaSOATRequest()
        {
        }
        
        public ConsultaSOATRequest(int codigoSucursal, int codigoRamo, long numeroPoliza, int numeroEndoso)
        {
            this.codigoSucursal = codigoSucursal;
            this.codigoRamo = codigoRamo;
            this.numeroPoliza = numeroPoliza;
            this.numeroEndoso = numeroEndoso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaSOATResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultaSOATResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ConsultaSOATResult;
        
        public ConsultaSOATResponse()
        {
        }
        
        public ConsultaSOATResponse(string ConsultaSOATResult)
        {
            this.ConsultaSOATResult = ConsultaSOATResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UsuarioToken", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UsuarioTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usuario_Token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> usuario_tran;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> usuario_estado;
        
        public UsuarioTokenRequest()
        {
        }
        
        public UsuarioTokenRequest(string usuario_Token, System.Nullable<int> usuario_tran, System.Nullable<int> usuario_estado)
        {
            this.usuario_Token = usuario_Token;
            this.usuario_tran = usuario_tran;
            this.usuario_estado = usuario_estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UsuarioTokenResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UsuarioTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UtilidadesSolidariaServiceReference.ArrayOfXElement UsuarioTokenResult;
        
        public UsuarioTokenResponse()
        {
        }
        
        public UsuarioTokenResponse(UtilidadesSolidariaServiceReference.ArrayOfXElement UsuarioTokenResult)
        {
            this.UsuarioTokenResult = UsuarioTokenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IWCFSolidariaUtilidadesChannel : UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WCFSolidariaUtilidadesClient : System.ServiceModel.ClientBase<UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades>, UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WCFSolidariaUtilidadesClient() : 
                base(WCFSolidariaUtilidadesClient.GetDefaultBinding(), WCFSolidariaUtilidadesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IWCFSolidariaUtilidades.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WCFSolidariaUtilidadesClient(EndpointConfiguration endpointConfiguration) : 
                base(WCFSolidariaUtilidadesClient.GetBindingForEndpoint(endpointConfiguration), WCFSolidariaUtilidadesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WCFSolidariaUtilidadesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WCFSolidariaUtilidadesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WCFSolidariaUtilidadesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WCFSolidariaUtilidadesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WCFSolidariaUtilidadesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.GenerarRegistroImpresionPolizaResponse> UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades.GenerarRegistroImpresionPolizaAsync(UtilidadesSolidariaServiceReference.GenerarRegistroImpresionPolizaRequest request)
        {
            return base.Channel.GenerarRegistroImpresionPolizaAsync(request);
        }
        
        public System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.GenerarRegistroImpresionPolizaResponse> GenerarRegistroImpresionPolizaAsync(UtilidadesSolidariaServiceReference.ImpresionPoliza pImpresionPoliza)
        {
            UtilidadesSolidariaServiceReference.GenerarRegistroImpresionPolizaRequest inValue = new UtilidadesSolidariaServiceReference.GenerarRegistroImpresionPolizaRequest();
            inValue.pImpresionPoliza = pImpresionPoliza;
            return ((UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades)(this)).GenerarRegistroImpresionPolizaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.InsertarDatosPolizaResponse> UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades.InsertarDatosPolizaAsync(UtilidadesSolidariaServiceReference.InsertarDatosPolizaRequest request)
        {
            return base.Channel.InsertarDatosPolizaAsync(request);
        }
        
        public System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.InsertarDatosPolizaResponse> InsertarDatosPolizaAsync(UtilidadesSolidariaServiceReference.InsertaDatosImpresion pInsertaImpresionPoliza)
        {
            UtilidadesSolidariaServiceReference.InsertarDatosPolizaRequest inValue = new UtilidadesSolidariaServiceReference.InsertarDatosPolizaRequest();
            inValue.pInsertaImpresionPoliza = pInsertaImpresionPoliza;
            return ((UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades)(this)).InsertarDatosPolizaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.ObtenerPDFResponse> UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades.ObtenerPDFAsync(UtilidadesSolidariaServiceReference.ObtenerPDFRequest request)
        {
            return base.Channel.ObtenerPDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.ObtenerPDFResponse> ObtenerPDFAsync(string RutaImpresion)
        {
            UtilidadesSolidariaServiceReference.ObtenerPDFRequest inValue = new UtilidadesSolidariaServiceReference.ObtenerPDFRequest();
            inValue.RutaImpresion = RutaImpresion;
            return ((UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades)(this)).ObtenerPDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.EncriptaResponse> UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades.EncriptaAsync(UtilidadesSolidariaServiceReference.EncriptaRequest request)
        {
            return base.Channel.EncriptaAsync(request);
        }
        
        public System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.EncriptaResponse> EncriptaAsync(string pParametro)
        {
            UtilidadesSolidariaServiceReference.EncriptaRequest inValue = new UtilidadesSolidariaServiceReference.EncriptaRequest();
            inValue.pParametro = pParametro;
            return ((UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades)(this)).EncriptaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.DesencriptaResponse> UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades.DesencriptaAsync(UtilidadesSolidariaServiceReference.DesencriptaRequest request)
        {
            return base.Channel.DesencriptaAsync(request);
        }
        
        public System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.DesencriptaResponse> DesencriptaAsync(string pParametro)
        {
            UtilidadesSolidariaServiceReference.DesencriptaRequest inValue = new UtilidadesSolidariaServiceReference.DesencriptaRequest();
            inValue.pParametro = pParametro;
            return ((UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades)(this)).DesencriptaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.AgregaClavePDFResponse> UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades.AgregaClavePDFAsync(UtilidadesSolidariaServiceReference.AgregaClavePDFRequest request)
        {
            return base.Channel.AgregaClavePDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.AgregaClavePDFResponse> AgregaClavePDFAsync(UtilidadesSolidariaServiceReference.pwdPDF pParametro)
        {
            UtilidadesSolidariaServiceReference.AgregaClavePDFRequest inValue = new UtilidadesSolidariaServiceReference.AgregaClavePDFRequest();
            inValue.pParametro = pParametro;
            return ((UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades)(this)).AgregaClavePDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.EnvioCorreoResponse> UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades.EnvioCorreoAsync(UtilidadesSolidariaServiceReference.EnvioCorreoRequest request)
        {
            return base.Channel.EnvioCorreoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.EnvioCorreoResponse> EnvioCorreoAsync(UtilidadesSolidariaServiceReference.Correo pDatosCorreo)
        {
            UtilidadesSolidariaServiceReference.EnvioCorreoRequest inValue = new UtilidadesSolidariaServiceReference.EnvioCorreoRequest();
            inValue.pDatosCorreo = pDatosCorreo;
            return ((UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades)(this)).EnvioCorreoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.GestionCorreoResponse> UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades.GestionCorreoAsync(UtilidadesSolidariaServiceReference.GestionCorreoRequest request)
        {
            return base.Channel.GestionCorreoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.GestionCorreoResponse> GestionCorreoAsync(UtilidadesSolidariaServiceReference.GestionCorreo pDatosGestionCorreo)
        {
            UtilidadesSolidariaServiceReference.GestionCorreoRequest inValue = new UtilidadesSolidariaServiceReference.GestionCorreoRequest();
            inValue.pDatosGestionCorreo = pDatosGestionCorreo;
            return ((UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades)(this)).GestionCorreoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.ImprimirPolizaSiseResponse> UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades.ImprimirPolizaSiseAsync(UtilidadesSolidariaServiceReference.ImprimirPolizaSiseRequest request)
        {
            return base.Channel.ImprimirPolizaSiseAsync(request);
        }
        
        public System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.ImprimirPolizaSiseResponse> ImprimirPolizaSiseAsync(UtilidadesSolidariaServiceReference.ImpresionPolizaSise pDatosPoliza)
        {
            UtilidadesSolidariaServiceReference.ImprimirPolizaSiseRequest inValue = new UtilidadesSolidariaServiceReference.ImprimirPolizaSiseRequest();
            inValue.pDatosPoliza = pDatosPoliza;
            return ((UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades)(this)).ImprimirPolizaSiseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.ConsultaSOATResponse> UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades.ConsultaSOATAsync(UtilidadesSolidariaServiceReference.ConsultaSOATRequest request)
        {
            return base.Channel.ConsultaSOATAsync(request);
        }
        
        public System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.ConsultaSOATResponse> ConsultaSOATAsync(int codigoSucursal, int codigoRamo, long numeroPoliza, int numeroEndoso)
        {
            UtilidadesSolidariaServiceReference.ConsultaSOATRequest inValue = new UtilidadesSolidariaServiceReference.ConsultaSOATRequest();
            inValue.codigoSucursal = codigoSucursal;
            inValue.codigoRamo = codigoRamo;
            inValue.numeroPoliza = numeroPoliza;
            inValue.numeroEndoso = numeroEndoso;
            return ((UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades)(this)).ConsultaSOATAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.UsuarioTokenResponse> UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades.UsuarioTokenAsync(UtilidadesSolidariaServiceReference.UsuarioTokenRequest request)
        {
            return base.Channel.UsuarioTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<UtilidadesSolidariaServiceReference.UsuarioTokenResponse> UsuarioTokenAsync(string usuario_Token, System.Nullable<int> usuario_tran, System.Nullable<int> usuario_estado)
        {
            UtilidadesSolidariaServiceReference.UsuarioTokenRequest inValue = new UtilidadesSolidariaServiceReference.UsuarioTokenRequest();
            inValue.usuario_Token = usuario_Token;
            inValue.usuario_tran = usuario_tran;
            inValue.usuario_estado = usuario_estado;
            return ((UtilidadesSolidariaServiceReference.IWCFSolidariaUtilidades)(this)).UsuarioTokenAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWCFSolidariaUtilidades))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWCFSolidariaUtilidades))
            {
                return new System.ServiceModel.EndpointAddress("http://192.1.3.183:8082/WCFSolidariaUtilidades/WCFSolidariaUtilidades.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WCFSolidariaUtilidadesClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IWCFSolidariaUtilidades);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WCFSolidariaUtilidadesClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IWCFSolidariaUtilidades);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWCFSolidariaUtilidades,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.0.2")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
