//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministracionPersonasServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    public partial class Persona : object
    {
        
        private int idPersonaField;
        
        private string TipoRespuestaField;
        
        private int CodigoField;
        
        private int TipoDocumentoField;
        
        private string DocumentoField;
        
        private int DigitoVerificacionField;
        
        private string PrimerNombreField;
        
        private string SegundoNombreField;
        
        private string PrimerApellidoField;
        
        private string SegundoApellidoField;
        
        private System.DateTime FechaNacimientoField;
        
        private string GeneroField;
        
        private string TipoPersonaField;
        
        private string OcupacionField;
        
        private AdministracionPersonasServiceReference.Direccion[] direccionField;
        
        private AdministracionPersonasServiceReference.Telefono[] telefonoField;
        
        private AdministracionPersonasServiceReference.Correo[] correoField;
        
        private AdministracionPersonasServiceReference.Financiera[] financieraField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idPersona
        {
            get
            {
                return this.idPersonaField;
            }
            set
            {
                this.idPersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TipoRespuesta
        {
            get
            {
                return this.TipoRespuestaField;
            }
            set
            {
                this.TipoRespuestaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int TipoDocumento
        {
            get
            {
                return this.TipoDocumentoField;
            }
            set
            {
                this.TipoDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Documento
        {
            get
            {
                return this.DocumentoField;
            }
            set
            {
                this.DocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int DigitoVerificacion
        {
            get
            {
                return this.DigitoVerificacionField;
            }
            set
            {
                this.DigitoVerificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string PrimerNombre
        {
            get
            {
                return this.PrimerNombreField;
            }
            set
            {
                this.PrimerNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SegundoNombre
        {
            get
            {
                return this.SegundoNombreField;
            }
            set
            {
                this.SegundoNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string PrimerApellido
        {
            get
            {
                return this.PrimerApellidoField;
            }
            set
            {
                this.PrimerApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string SegundoApellido
        {
            get
            {
                return this.SegundoApellidoField;
            }
            set
            {
                this.SegundoApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Genero
        {
            get
            {
                return this.GeneroField;
            }
            set
            {
                this.GeneroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string TipoPersona
        {
            get
            {
                return this.TipoPersonaField;
            }
            set
            {
                this.TipoPersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Ocupacion
        {
            get
            {
                return this.OcupacionField;
            }
            set
            {
                this.OcupacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public AdministracionPersonasServiceReference.Direccion[] direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public AdministracionPersonasServiceReference.Telefono[] telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public AdministracionPersonasServiceReference.Correo[] correo
        {
            get
            {
                return this.correoField;
            }
            set
            {
                this.correoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public AdministracionPersonasServiceReference.Financiera[] financiera
        {
            get
            {
                return this.financieraField;
            }
            set
            {
                this.financieraField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Direccion", Namespace="http://tempuri.org/")]
    public partial class Direccion : object
    {
        
        private int idPersonaField;
        
        private int TipoDireccionField;
        
        private string DireccionPersonaField;
        
        private int CodigoPaisField;
        
        private int CodigoDepartamentoField;
        
        private int CodigoMunicipioField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idPersona
        {
            get
            {
                return this.idPersonaField;
            }
            set
            {
                this.idPersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int TipoDireccion
        {
            get
            {
                return this.TipoDireccionField;
            }
            set
            {
                this.TipoDireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DireccionPersona
        {
            get
            {
                return this.DireccionPersonaField;
            }
            set
            {
                this.DireccionPersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CodigoPais
        {
            get
            {
                return this.CodigoPaisField;
            }
            set
            {
                this.CodigoPaisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int CodigoDepartamento
        {
            get
            {
                return this.CodigoDepartamentoField;
            }
            set
            {
                this.CodigoDepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int CodigoMunicipio
        {
            get
            {
                return this.CodigoMunicipioField;
            }
            set
            {
                this.CodigoMunicipioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Telefono", Namespace="http://tempuri.org/")]
    public partial class Telefono : object
    {
        
        private int idPersonaField;
        
        private int TipoTelefonoField;
        
        private string NumeroTelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idPersona
        {
            get
            {
                return this.idPersonaField;
            }
            set
            {
                this.idPersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int TipoTelefono
        {
            get
            {
                return this.TipoTelefonoField;
            }
            set
            {
                this.TipoTelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NumeroTelefono
        {
            get
            {
                return this.NumeroTelefonoField;
            }
            set
            {
                this.NumeroTelefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Correo", Namespace="http://tempuri.org/")]
    public partial class Correo : object
    {
        
        private int idPersonaField;
        
        private int TipoCorreoField;
        
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idPersona
        {
            get
            {
                return this.idPersonaField;
            }
            set
            {
                this.idPersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int TipoCorreo
        {
            get
            {
                return this.TipoCorreoField;
            }
            set
            {
                this.TipoCorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CorreoElectronico
        {
            get
            {
                return this.CorreoElectronicoField;
            }
            set
            {
                this.CorreoElectronicoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Financiera", Namespace="http://tempuri.org/")]
    public partial class Financiera : object
    {
        
        private int idPersonaField;
        
        private int TipoFinancieraField;
        
        private string InformacionFinancieraField;
        
        private double ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idPersona
        {
            get
            {
                return this.idPersonaField;
            }
            set
            {
                this.idPersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int TipoFinanciera
        {
            get
            {
                return this.TipoFinancieraField;
            }
            set
            {
                this.TipoFinancieraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string InformacionFinanciera
        {
            get
            {
                return this.InformacionFinancieraField;
            }
            set
            {
                this.InformacionFinancieraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaActualizarPersona", Namespace="http://tempuri.org/")]
    public partial class RespuestaActualizarPersona : object
    {
        
        private string SeverityField;
        
        private string DescripcionEstadoField;
        
        private int CodigoEstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Severity
        {
            get
            {
                return this.SeverityField;
            }
            set
            {
                this.SeverityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DescripcionEstado
        {
            get
            {
                return this.DescripcionEstadoField;
            }
            set
            {
                this.DescripcionEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int CodigoEstado
        {
            get
            {
                return this.CodigoEstadoField;
            }
            set
            {
                this.CodigoEstadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonaGral", Namespace="http://tempuri.org/")]
    public partial class PersonaGral : object
    {
        
        private int CodigoBeneficiarioField;
        
        private string EstadoCivilField;
        
        private int CodigoEstadoCivilField;
        
        private int CodigoTipoAseguradoField;
        
        private string TipoAseguradoField;
        
        private string TipoEmpresaField;
        
        private int CodigoTipoEmpresaField;
        
        private string ActividadEconomicaField;
        
        private int CodigoActividadEconomicaField;
        
        private string ImportanciaAseguradoField;
        
        private int CodigoImportanciaAseguradoField;
        
        private int idPersonaField;
        
        private string TipoRespuestaField;
        
        private int CodigoField;
        
        private int TipoDocumentoField;
        
        private string DocumentoField;
        
        private int DigitoVerificacionField;
        
        private string PrimerNombreField;
        
        private string SegundoNombreField;
        
        private string PrimerApellidoField;
        
        private string SegundoApellidoField;
        
        private System.DateTime FechaNacimientoField;
        
        private string GeneroField;
        
        private string TipoPersonaField;
        
        private string OcupacionField;
        
        private AdministracionPersonasServiceReference.DireccionGral[] direccionField;
        
        private AdministracionPersonasServiceReference.TelefonoGral[] telefonoField;
        
        private AdministracionPersonasServiceReference.CorreoGral[] correoField;
        
        private AdministracionPersonasServiceReference.FinancieraGral[] financieraField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoBeneficiario
        {
            get
            {
                return this.CodigoBeneficiarioField;
            }
            set
            {
                this.CodigoBeneficiarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EstadoCivil
        {
            get
            {
                return this.EstadoCivilField;
            }
            set
            {
                this.EstadoCivilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int CodigoEstadoCivil
        {
            get
            {
                return this.CodigoEstadoCivilField;
            }
            set
            {
                this.CodigoEstadoCivilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CodigoTipoAsegurado
        {
            get
            {
                return this.CodigoTipoAseguradoField;
            }
            set
            {
                this.CodigoTipoAseguradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TipoAsegurado
        {
            get
            {
                return this.TipoAseguradoField;
            }
            set
            {
                this.TipoAseguradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TipoEmpresa
        {
            get
            {
                return this.TipoEmpresaField;
            }
            set
            {
                this.TipoEmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int CodigoTipoEmpresa
        {
            get
            {
                return this.CodigoTipoEmpresaField;
            }
            set
            {
                this.CodigoTipoEmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ActividadEconomica
        {
            get
            {
                return this.ActividadEconomicaField;
            }
            set
            {
                this.ActividadEconomicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int CodigoActividadEconomica
        {
            get
            {
                return this.CodigoActividadEconomicaField;
            }
            set
            {
                this.CodigoActividadEconomicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ImportanciaAsegurado
        {
            get
            {
                return this.ImportanciaAseguradoField;
            }
            set
            {
                this.ImportanciaAseguradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int CodigoImportanciaAsegurado
        {
            get
            {
                return this.CodigoImportanciaAseguradoField;
            }
            set
            {
                this.CodigoImportanciaAseguradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int idPersona
        {
            get
            {
                return this.idPersonaField;
            }
            set
            {
                this.idPersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string TipoRespuesta
        {
            get
            {
                return this.TipoRespuestaField;
            }
            set
            {
                this.TipoRespuestaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public int Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public int TipoDocumento
        {
            get
            {
                return this.TipoDocumentoField;
            }
            set
            {
                this.TipoDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Documento
        {
            get
            {
                return this.DocumentoField;
            }
            set
            {
                this.DocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public int DigitoVerificacion
        {
            get
            {
                return this.DigitoVerificacionField;
            }
            set
            {
                this.DigitoVerificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string PrimerNombre
        {
            get
            {
                return this.PrimerNombreField;
            }
            set
            {
                this.PrimerNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string SegundoNombre
        {
            get
            {
                return this.SegundoNombreField;
            }
            set
            {
                this.SegundoNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string PrimerApellido
        {
            get
            {
                return this.PrimerApellidoField;
            }
            set
            {
                this.PrimerApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string SegundoApellido
        {
            get
            {
                return this.SegundoApellidoField;
            }
            set
            {
                this.SegundoApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public System.DateTime FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string Genero
        {
            get
            {
                return this.GeneroField;
            }
            set
            {
                this.GeneroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string TipoPersona
        {
            get
            {
                return this.TipoPersonaField;
            }
            set
            {
                this.TipoPersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string Ocupacion
        {
            get
            {
                return this.OcupacionField;
            }
            set
            {
                this.OcupacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public AdministracionPersonasServiceReference.DireccionGral[] direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public AdministracionPersonasServiceReference.TelefonoGral[] telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public AdministracionPersonasServiceReference.CorreoGral[] correo
        {
            get
            {
                return this.correoField;
            }
            set
            {
                this.correoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public AdministracionPersonasServiceReference.FinancieraGral[] financiera
        {
            get
            {
                return this.financieraField;
            }
            set
            {
                this.financieraField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DireccionGral", Namespace="http://tempuri.org/")]
    public partial class DireccionGral : object
    {
        
        private int idPersonaField;
        
        private int TipoDireccionField;
        
        private string DireccionPersonaField;
        
        private int CodigoPaisField;
        
        private int CodigoDepartamentoField;
        
        private int CodigoMunicipioField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idPersona
        {
            get
            {
                return this.idPersonaField;
            }
            set
            {
                this.idPersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int TipoDireccion
        {
            get
            {
                return this.TipoDireccionField;
            }
            set
            {
                this.TipoDireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DireccionPersona
        {
            get
            {
                return this.DireccionPersonaField;
            }
            set
            {
                this.DireccionPersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CodigoPais
        {
            get
            {
                return this.CodigoPaisField;
            }
            set
            {
                this.CodigoPaisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int CodigoDepartamento
        {
            get
            {
                return this.CodigoDepartamentoField;
            }
            set
            {
                this.CodigoDepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int CodigoMunicipio
        {
            get
            {
                return this.CodigoMunicipioField;
            }
            set
            {
                this.CodigoMunicipioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TelefonoGral", Namespace="http://tempuri.org/")]
    public partial class TelefonoGral : object
    {
        
        private int idPersonaField;
        
        private int TipoTelefonoField;
        
        private string NumeroTelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idPersona
        {
            get
            {
                return this.idPersonaField;
            }
            set
            {
                this.idPersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int TipoTelefono
        {
            get
            {
                return this.TipoTelefonoField;
            }
            set
            {
                this.TipoTelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NumeroTelefono
        {
            get
            {
                return this.NumeroTelefonoField;
            }
            set
            {
                this.NumeroTelefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CorreoGral", Namespace="http://tempuri.org/")]
    public partial class CorreoGral : object
    {
        
        private int idPersonaField;
        
        private int TipoCorreoField;
        
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idPersona
        {
            get
            {
                return this.idPersonaField;
            }
            set
            {
                this.idPersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int TipoCorreo
        {
            get
            {
                return this.TipoCorreoField;
            }
            set
            {
                this.TipoCorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CorreoElectronico
        {
            get
            {
                return this.CorreoElectronicoField;
            }
            set
            {
                this.CorreoElectronicoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FinancieraGral", Namespace="http://tempuri.org/")]
    public partial class FinancieraGral : object
    {
        
        private int idPersonaField;
        
        private int TipoFinancieraField;
        
        private string InformacionFinancieraField;
        
        private double ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idPersona
        {
            get
            {
                return this.idPersonaField;
            }
            set
            {
                this.idPersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int TipoFinanciera
        {
            get
            {
                return this.TipoFinancieraField;
            }
            set
            {
                this.TipoFinancieraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string InformacionFinanciera
        {
            get
            {
                return this.InformacionFinancieraField;
            }
            set
            {
                this.InformacionFinancieraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CalidadDatosMovimientos", Namespace="http://tempuri.org/")]
    public partial class CalidadDatosMovimientos : object
    {
        
        private int IdCalidadDatosContactCenterMovimientosField;
        
        private int CodigoTipoDocumentoField;
        
        private string NumeroDocumentoField;
        
        private int CodigoEstadoProcesoField;
        
        private bool SNProcesadoField;
        
        private int CodigoProcesoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdCalidadDatosContactCenterMovimientos
        {
            get
            {
                return this.IdCalidadDatosContactCenterMovimientosField;
            }
            set
            {
                this.IdCalidadDatosContactCenterMovimientosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int CodigoTipoDocumento
        {
            get
            {
                return this.CodigoTipoDocumentoField;
            }
            set
            {
                this.CodigoTipoDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NumeroDocumento
        {
            get
            {
                return this.NumeroDocumentoField;
            }
            set
            {
                this.NumeroDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CodigoEstadoProceso
        {
            get
            {
                return this.CodigoEstadoProcesoField;
            }
            set
            {
                this.CodigoEstadoProcesoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool SNProcesado
        {
            get
            {
                return this.SNProcesadoField;
            }
            set
            {
                this.SNProcesadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int CodigoProceso
        {
            get
            {
                return this.CodigoProcesoField;
            }
            set
            {
                this.CodigoProcesoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://tempuri.org/")]
    public partial class Respuesta : object
    {
        
        private string SeverityField;
        
        private string DescripcionEstadoField;
        
        private int CodigoEstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Severity
        {
            get
            {
                return this.SeverityField;
            }
            set
            {
                this.SeverityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DescripcionEstado
        {
            get
            {
                return this.DescripcionEstadoField;
            }
            set
            {
                this.DescripcionEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int CodigoEstado
        {
            get
            {
                return this.CodigoEstadoField;
            }
            set
            {
                this.CodigoEstadoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdministracionPersonasServiceReference.IWCFAdministracionPersonas")]
    public interface IWCFAdministracionPersonas
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAdministracionPersonas/TraerPersona", ReplyAction="http://tempuri.org/IWCFAdministracionPersonas/TraerPersonaResponse")]
        System.Threading.Tasks.Task<AdministracionPersonasServiceReference.TraerPersonaResponse> TraerPersonaAsync(AdministracionPersonasServiceReference.TraerPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAdministracionPersonas/ActualizarPersona", ReplyAction="http://tempuri.org/IWCFAdministracionPersonas/ActualizarPersonaResponse")]
        System.Threading.Tasks.Task<AdministracionPersonasServiceReference.ActualizarPersonaResponse> ActualizarPersonaAsync(AdministracionPersonasServiceReference.ActualizarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAdministracionPersonas/TraerPersonaGral", ReplyAction="http://tempuri.org/IWCFAdministracionPersonas/TraerPersonaGralResponse")]
        System.Threading.Tasks.Task<AdministracionPersonasServiceReference.TraerPersonaGralResponse> TraerPersonaGralAsync(AdministracionPersonasServiceReference.TraerPersonaGralRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAdministracionPersonas/RegistroMovimientoCalidadDatos", ReplyAction="http://tempuri.org/IWCFAdministracionPersonas/RegistroMovimientoCalidadDatosRespo" +
            "nse")]
        System.Threading.Tasks.Task<AdministracionPersonasServiceReference.RegistroMovimientoCalidadDatosResponse> RegistroMovimientoCalidadDatosAsync(AdministracionPersonasServiceReference.RegistroMovimientoCalidadDatosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraerPersonaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraerPersona", Namespace="http://tempuri.org/", Order=0)]
        public AdministracionPersonasServiceReference.TraerPersonaRequestBody Body;
        
        public TraerPersonaRequest()
        {
        }
        
        public TraerPersonaRequest(AdministracionPersonasServiceReference.TraerPersonaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TraerPersonaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ParametroXML;
        
        public TraerPersonaRequestBody()
        {
        }
        
        public TraerPersonaRequestBody(string ParametroXML)
        {
            this.ParametroXML = ParametroXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraerPersonaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraerPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public AdministracionPersonasServiceReference.TraerPersonaResponseBody Body;
        
        public TraerPersonaResponse()
        {
        }
        
        public TraerPersonaResponse(AdministracionPersonasServiceReference.TraerPersonaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TraerPersonaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AdministracionPersonasServiceReference.Persona TraerPersonaResult;
        
        public TraerPersonaResponseBody()
        {
        }
        
        public TraerPersonaResponseBody(AdministracionPersonasServiceReference.Persona TraerPersonaResult)
        {
            this.TraerPersonaResult = TraerPersonaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarPersonaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarPersona", Namespace="http://tempuri.org/", Order=0)]
        public AdministracionPersonasServiceReference.ActualizarPersonaRequestBody Body;
        
        public ActualizarPersonaRequest()
        {
        }
        
        public ActualizarPersonaRequest(AdministracionPersonasServiceReference.ActualizarPersonaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarPersonaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AdministracionPersonasServiceReference.Persona pPersona;
        
        public ActualizarPersonaRequestBody()
        {
        }
        
        public ActualizarPersonaRequestBody(AdministracionPersonasServiceReference.Persona pPersona)
        {
            this.pPersona = pPersona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarPersonaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public AdministracionPersonasServiceReference.ActualizarPersonaResponseBody Body;
        
        public ActualizarPersonaResponse()
        {
        }
        
        public ActualizarPersonaResponse(AdministracionPersonasServiceReference.ActualizarPersonaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarPersonaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AdministracionPersonasServiceReference.RespuestaActualizarPersona ActualizarPersonaResult;
        
        public ActualizarPersonaResponseBody()
        {
        }
        
        public ActualizarPersonaResponseBody(AdministracionPersonasServiceReference.RespuestaActualizarPersona ActualizarPersonaResult)
        {
            this.ActualizarPersonaResult = ActualizarPersonaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraerPersonaGralRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraerPersonaGral", Namespace="http://tempuri.org/", Order=0)]
        public AdministracionPersonasServiceReference.TraerPersonaGralRequestBody Body;
        
        public TraerPersonaGralRequest()
        {
        }
        
        public TraerPersonaGralRequest(AdministracionPersonasServiceReference.TraerPersonaGralRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TraerPersonaGralRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ParametroXML;
        
        public TraerPersonaGralRequestBody()
        {
        }
        
        public TraerPersonaGralRequestBody(string ParametroXML)
        {
            this.ParametroXML = ParametroXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraerPersonaGralResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraerPersonaGralResponse", Namespace="http://tempuri.org/", Order=0)]
        public AdministracionPersonasServiceReference.TraerPersonaGralResponseBody Body;
        
        public TraerPersonaGralResponse()
        {
        }
        
        public TraerPersonaGralResponse(AdministracionPersonasServiceReference.TraerPersonaGralResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TraerPersonaGralResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AdministracionPersonasServiceReference.PersonaGral TraerPersonaGralResult;
        
        public TraerPersonaGralResponseBody()
        {
        }
        
        public TraerPersonaGralResponseBody(AdministracionPersonasServiceReference.PersonaGral TraerPersonaGralResult)
        {
            this.TraerPersonaGralResult = TraerPersonaGralResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroMovimientoCalidadDatosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistroMovimientoCalidadDatos", Namespace="http://tempuri.org/", Order=0)]
        public AdministracionPersonasServiceReference.RegistroMovimientoCalidadDatosRequestBody Body;
        
        public RegistroMovimientoCalidadDatosRequest()
        {
        }
        
        public RegistroMovimientoCalidadDatosRequest(AdministracionPersonasServiceReference.RegistroMovimientoCalidadDatosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistroMovimientoCalidadDatosRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AdministracionPersonasServiceReference.CalidadDatosMovimientos pDatosCalidad;
        
        public RegistroMovimientoCalidadDatosRequestBody()
        {
        }
        
        public RegistroMovimientoCalidadDatosRequestBody(AdministracionPersonasServiceReference.CalidadDatosMovimientos pDatosCalidad)
        {
            this.pDatosCalidad = pDatosCalidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroMovimientoCalidadDatosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistroMovimientoCalidadDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public AdministracionPersonasServiceReference.RegistroMovimientoCalidadDatosResponseBody Body;
        
        public RegistroMovimientoCalidadDatosResponse()
        {
        }
        
        public RegistroMovimientoCalidadDatosResponse(AdministracionPersonasServiceReference.RegistroMovimientoCalidadDatosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistroMovimientoCalidadDatosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AdministracionPersonasServiceReference.Respuesta[] RegistroMovimientoCalidadDatosResult;
        
        public RegistroMovimientoCalidadDatosResponseBody()
        {
        }
        
        public RegistroMovimientoCalidadDatosResponseBody(AdministracionPersonasServiceReference.Respuesta[] RegistroMovimientoCalidadDatosResult)
        {
            this.RegistroMovimientoCalidadDatosResult = RegistroMovimientoCalidadDatosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IWCFAdministracionPersonasChannel : AdministracionPersonasServiceReference.IWCFAdministracionPersonas, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WCFAdministracionPersonasClient : System.ServiceModel.ClientBase<AdministracionPersonasServiceReference.IWCFAdministracionPersonas>, AdministracionPersonasServiceReference.IWCFAdministracionPersonas
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WCFAdministracionPersonasClient() : 
                base(WCFAdministracionPersonasClient.GetDefaultBinding(), WCFAdministracionPersonasClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IWCFAdministracionPersonas.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WCFAdministracionPersonasClient(EndpointConfiguration endpointConfiguration) : 
                base(WCFAdministracionPersonasClient.GetBindingForEndpoint(endpointConfiguration), WCFAdministracionPersonasClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WCFAdministracionPersonasClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WCFAdministracionPersonasClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WCFAdministracionPersonasClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WCFAdministracionPersonasClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WCFAdministracionPersonasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AdministracionPersonasServiceReference.TraerPersonaResponse> AdministracionPersonasServiceReference.IWCFAdministracionPersonas.TraerPersonaAsync(AdministracionPersonasServiceReference.TraerPersonaRequest request)
        {
            return base.Channel.TraerPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AdministracionPersonasServiceReference.TraerPersonaResponse> TraerPersonaAsync(string ParametroXML)
        {
            AdministracionPersonasServiceReference.TraerPersonaRequest inValue = new AdministracionPersonasServiceReference.TraerPersonaRequest();
            inValue.Body = new AdministracionPersonasServiceReference.TraerPersonaRequestBody();
            inValue.Body.ParametroXML = ParametroXML;
            return ((AdministracionPersonasServiceReference.IWCFAdministracionPersonas)(this)).TraerPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AdministracionPersonasServiceReference.ActualizarPersonaResponse> AdministracionPersonasServiceReference.IWCFAdministracionPersonas.ActualizarPersonaAsync(AdministracionPersonasServiceReference.ActualizarPersonaRequest request)
        {
            return base.Channel.ActualizarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AdministracionPersonasServiceReference.ActualizarPersonaResponse> ActualizarPersonaAsync(AdministracionPersonasServiceReference.Persona pPersona)
        {
            AdministracionPersonasServiceReference.ActualizarPersonaRequest inValue = new AdministracionPersonasServiceReference.ActualizarPersonaRequest();
            inValue.Body = new AdministracionPersonasServiceReference.ActualizarPersonaRequestBody();
            inValue.Body.pPersona = pPersona;
            return ((AdministracionPersonasServiceReference.IWCFAdministracionPersonas)(this)).ActualizarPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AdministracionPersonasServiceReference.TraerPersonaGralResponse> AdministracionPersonasServiceReference.IWCFAdministracionPersonas.TraerPersonaGralAsync(AdministracionPersonasServiceReference.TraerPersonaGralRequest request)
        {
            return base.Channel.TraerPersonaGralAsync(request);
        }
        
        public System.Threading.Tasks.Task<AdministracionPersonasServiceReference.TraerPersonaGralResponse> TraerPersonaGralAsync(string ParametroXML)
        {
            AdministracionPersonasServiceReference.TraerPersonaGralRequest inValue = new AdministracionPersonasServiceReference.TraerPersonaGralRequest();
            inValue.Body = new AdministracionPersonasServiceReference.TraerPersonaGralRequestBody();
            inValue.Body.ParametroXML = ParametroXML;
            return ((AdministracionPersonasServiceReference.IWCFAdministracionPersonas)(this)).TraerPersonaGralAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AdministracionPersonasServiceReference.RegistroMovimientoCalidadDatosResponse> AdministracionPersonasServiceReference.IWCFAdministracionPersonas.RegistroMovimientoCalidadDatosAsync(AdministracionPersonasServiceReference.RegistroMovimientoCalidadDatosRequest request)
        {
            return base.Channel.RegistroMovimientoCalidadDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<AdministracionPersonasServiceReference.RegistroMovimientoCalidadDatosResponse> RegistroMovimientoCalidadDatosAsync(AdministracionPersonasServiceReference.CalidadDatosMovimientos pDatosCalidad)
        {
            AdministracionPersonasServiceReference.RegistroMovimientoCalidadDatosRequest inValue = new AdministracionPersonasServiceReference.RegistroMovimientoCalidadDatosRequest();
            inValue.Body = new AdministracionPersonasServiceReference.RegistroMovimientoCalidadDatosRequestBody();
            inValue.Body.pDatosCalidad = pDatosCalidad;
            return ((AdministracionPersonasServiceReference.IWCFAdministracionPersonas)(this)).RegistroMovimientoCalidadDatosAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWCFAdministracionPersonas))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWCFAdministracionPersonas))
            {
                return new System.ServiceModel.EndpointAddress("http://192.1.3.183:8082/WCFAdminPersonas/WCFAdministracionPersonas.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WCFAdministracionPersonasClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IWCFAdministracionPersonas);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WCFAdministracionPersonasClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IWCFAdministracionPersonas);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWCFAdministracionPersonas,
        }
    }
}
