//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonasServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ramo", Namespace="http://schemas.datacontract.org/2004/07/TablasParametrizacionPersonas.Entidades")]
    public partial class Ramo : object
    {
        
        private int CodigoRamoField;
        
        private string NombreAbreviadoField;
        
        private string NombreRamoField;
        
        private string NombreReducidoField;
        
        private bool SnIvaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoRamo
        {
            get
            {
                return this.CodigoRamoField;
            }
            set
            {
                this.CodigoRamoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreAbreviado
        {
            get
            {
                return this.NombreAbreviadoField;
            }
            set
            {
                this.NombreAbreviadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreRamo
        {
            get
            {
                return this.NombreRamoField;
            }
            set
            {
                this.NombreRamoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreReducido
        {
            get
            {
                return this.NombreReducidoField;
            }
            set
            {
                this.NombreReducidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SnIva
        {
            get
            {
                return this.SnIvaField;
            }
            set
            {
                this.SnIvaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubRamo", Namespace="http://schemas.datacontract.org/2004/07/TablasParametrizacionPersonas.Entidades")]
    public partial class SubRamo : object
    {
        
        private int CodigoRamoField;
        
        private int CodigoSubRamoField;
        
        private string NombreAbreviadoField;
        
        private string NombreRamoField;
        
        private string NombreReducidoField;
        
        private string NombreSubRamoField;
        
        private bool SiNoPerfilEdadesField;
        
        private bool SiNoPerfilValoresField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoRamo
        {
            get
            {
                return this.CodigoRamoField;
            }
            set
            {
                this.CodigoRamoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoSubRamo
        {
            get
            {
                return this.CodigoSubRamoField;
            }
            set
            {
                this.CodigoSubRamoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreAbreviado
        {
            get
            {
                return this.NombreAbreviadoField;
            }
            set
            {
                this.NombreAbreviadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreRamo
        {
            get
            {
                return this.NombreRamoField;
            }
            set
            {
                this.NombreRamoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreReducido
        {
            get
            {
                return this.NombreReducidoField;
            }
            set
            {
                this.NombreReducidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreSubRamo
        {
            get
            {
                return this.NombreSubRamoField;
            }
            set
            {
                this.NombreSubRamoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SiNoPerfilEdades
        {
            get
            {
                return this.SiNoPerfilEdadesField;
            }
            set
            {
                this.SiNoPerfilEdadesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SiNoPerfilValores
        {
            get
            {
                return this.SiNoPerfilValoresField;
            }
            set
            {
                this.SiNoPerfilValoresField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sector", Namespace="http://schemas.datacontract.org/2004/07/TablasParametrizacionPersonas.Entidades")]
    public partial class Sector : object
    {
        
        private int CodigoSectorField;
        
        private string NombreSectorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoSector
        {
            get
            {
                return this.CodigoSectorField;
            }
            set
            {
                this.CodigoSectorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreSector
        {
            get
            {
                return this.NombreSectorField;
            }
            set
            {
                this.NombreSectorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tasa", Namespace="http://schemas.datacontract.org/2004/07/TablasParametrizacionPersonas.Entidades")]
    public partial class Tasa : object
    {
        
        private int CodigoTasaField;
        
        private int CodigoTasaDosField;
        
        private string NombreTasaField;
        
        private bool SiNoObligatorioField;
        
        private bool SiNoRangoEdadesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoTasa
        {
            get
            {
                return this.CodigoTasaField;
            }
            set
            {
                this.CodigoTasaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoTasaDos
        {
            get
            {
                return this.CodigoTasaDosField;
            }
            set
            {
                this.CodigoTasaDosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreTasa
        {
            get
            {
                return this.NombreTasaField;
            }
            set
            {
                this.NombreTasaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SiNoObligatorio
        {
            get
            {
                return this.SiNoObligatorioField;
            }
            set
            {
                this.SiNoObligatorioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SiNoRangoEdades
        {
            get
            {
                return this.SiNoRangoEdadesField;
            }
            set
            {
                this.SiNoRangoEdadesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RiesgoActividad", Namespace="http://schemas.datacontract.org/2004/07/TablasParametrizacionPersonas.Entidades")]
    public partial class RiesgoActividad : object
    {
        
        private int CodigoRiesgoActividadField;
        
        private string DetalleRiesgoActividadField;
        
        private string NombreRiesgoActividadField;
        
        private bool SiNoAutorizacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoRiesgoActividad
        {
            get
            {
                return this.CodigoRiesgoActividadField;
            }
            set
            {
                this.CodigoRiesgoActividadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetalleRiesgoActividad
        {
            get
            {
                return this.DetalleRiesgoActividadField;
            }
            set
            {
                this.DetalleRiesgoActividadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreRiesgoActividad
        {
            get
            {
                return this.NombreRiesgoActividadField;
            }
            set
            {
                this.NombreRiesgoActividadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SiNoAutorizacion
        {
            get
            {
                return this.SiNoAutorizacionField;
            }
            set
            {
                this.SiNoAutorizacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoNegocio", Namespace="http://schemas.datacontract.org/2004/07/TablasParametrizacionPersonas.Entidades")]
    public partial class TipoNegocio : object
    {
        
        private int CodigoTipoNegocioField;
        
        private string NombreTipoNegocioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoTipoNegocio
        {
            get
            {
                return this.CodigoTipoNegocioField;
            }
            set
            {
                this.CodigoTipoNegocioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreTipoNegocio
        {
            get
            {
                return this.NombreTipoNegocioField;
            }
            set
            {
                this.NombreTipoNegocioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoContratacion", Namespace="http://schemas.datacontract.org/2004/07/TablasParametrizacionPersonas.Entidades")]
    public partial class TipoContratacion : object
    {
        
        private int CodigoTipoContratacionField;
        
        private string NombreTipoContratacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoTipoContratacion
        {
            get
            {
                return this.CodigoTipoContratacionField;
            }
            set
            {
                this.CodigoTipoContratacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreTipoContratacion
        {
            get
            {
                return this.NombreTipoContratacionField;
            }
            set
            {
                this.NombreTipoContratacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoSumaAsegurada", Namespace="http://schemas.datacontract.org/2004/07/TablasParametrizacionPersonas.Entidades")]
    public partial class TipoSumaAsegurada : object
    {
        
        private int CodigoTipoSumaAseguradaField;
        
        private string NombreTipoSumaAseguradaField;
        
        private bool SiNoTasaMensualSlipField;
        
        private decimal ValorSalarioMinimoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoTipoSumaAsegurada
        {
            get
            {
                return this.CodigoTipoSumaAseguradaField;
            }
            set
            {
                this.CodigoTipoSumaAseguradaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreTipoSumaAsegurada
        {
            get
            {
                return this.NombreTipoSumaAseguradaField;
            }
            set
            {
                this.NombreTipoSumaAseguradaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SiNoTasaMensualSlip
        {
            get
            {
                return this.SiNoTasaMensualSlipField;
            }
            set
            {
                this.SiNoTasaMensualSlipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorSalarioMinimo
        {
            get
            {
                return this.ValorSalarioMinimoField;
            }
            set
            {
                this.ValorSalarioMinimoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDocumento", Namespace="http://schemas.datacontract.org/2004/07/TablasParametrizacionPersonas.Entidades")]
    public partial class TipoDocumento : object
    {
        
        private int CodigoTipoDocumentoField;
        
        private string NombreReducidoField;
        
        private string NombreTipoDocumentoField;
        
        private bool SiNoAlfanumericoField;
        
        private string TipoPersonaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoTipoDocumento
        {
            get
            {
                return this.CodigoTipoDocumentoField;
            }
            set
            {
                this.CodigoTipoDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreReducido
        {
            get
            {
                return this.NombreReducidoField;
            }
            set
            {
                this.NombreReducidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreTipoDocumento
        {
            get
            {
                return this.NombreTipoDocumentoField;
            }
            set
            {
                this.NombreTipoDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SiNoAlfanumerico
        {
            get
            {
                return this.SiNoAlfanumericoField;
            }
            set
            {
                this.SiNoAlfanumericoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoPersona
        {
            get
            {
                return this.TipoPersonaField;
            }
            set
            {
                this.TipoPersonaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Amparo", Namespace="http://schemas.datacontract.org/2004/07/TablasParametrizacionPersonas.Entidades")]
    public partial class Amparo : object
    {
        
        private int CodigoAmparoField;
        
        private int CodigoGrupoAmparoField;
        
        private int EdadMaximaIngresoField;
        
        private int EdadMaximaPermanenciaField;
        
        private int EdadMinimaIngresoField;
        
        private PersonasServiceReference.Modalidad ModalidadField;
        
        private string NombreAmparoField;
        
        private string NombreCortoGrupoAmparoField;
        
        private string NombreGrupoAmparoField;
        
        private bool SiNoAdicionalField;
        
        private bool SiNoBasicoField;
        
        private bool SiNoPorcentajeBasicoField;
        
        private bool SiNoRequiereEdadesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoAmparo
        {
            get
            {
                return this.CodigoAmparoField;
            }
            set
            {
                this.CodigoAmparoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoGrupoAmparo
        {
            get
            {
                return this.CodigoGrupoAmparoField;
            }
            set
            {
                this.CodigoGrupoAmparoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EdadMaximaIngreso
        {
            get
            {
                return this.EdadMaximaIngresoField;
            }
            set
            {
                this.EdadMaximaIngresoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EdadMaximaPermanencia
        {
            get
            {
                return this.EdadMaximaPermanenciaField;
            }
            set
            {
                this.EdadMaximaPermanenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EdadMinimaIngreso
        {
            get
            {
                return this.EdadMinimaIngresoField;
            }
            set
            {
                this.EdadMinimaIngresoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PersonasServiceReference.Modalidad Modalidad
        {
            get
            {
                return this.ModalidadField;
            }
            set
            {
                this.ModalidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreAmparo
        {
            get
            {
                return this.NombreAmparoField;
            }
            set
            {
                this.NombreAmparoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCortoGrupoAmparo
        {
            get
            {
                return this.NombreCortoGrupoAmparoField;
            }
            set
            {
                this.NombreCortoGrupoAmparoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreGrupoAmparo
        {
            get
            {
                return this.NombreGrupoAmparoField;
            }
            set
            {
                this.NombreGrupoAmparoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SiNoAdicional
        {
            get
            {
                return this.SiNoAdicionalField;
            }
            set
            {
                this.SiNoAdicionalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SiNoBasico
        {
            get
            {
                return this.SiNoBasicoField;
            }
            set
            {
                this.SiNoBasicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SiNoPorcentajeBasico
        {
            get
            {
                return this.SiNoPorcentajeBasicoField;
            }
            set
            {
                this.SiNoPorcentajeBasicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SiNoRequiereEdades
        {
            get
            {
                return this.SiNoRequiereEdadesField;
            }
            set
            {
                this.SiNoRequiereEdadesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Modalidad", Namespace="http://schemas.datacontract.org/2004/07/TablasParametrizacionPersonas.Entidades")]
    public partial class Modalidad : object
    {
        
        private int CodigoField;
        
        private string NombreField;
        
        private PersonasServiceReference.Value[] ValoresField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PersonasServiceReference.Value[] Valores
        {
            get
            {
                return this.ValoresField;
            }
            set
            {
                this.ValoresField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Value", Namespace="http://schemas.datacontract.org/2004/07/TablasParametrizacionPersonas.Entidades")]
    public partial class Value : object
    {
        
        private double TopeField;
        
        private double ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Tope
        {
            get
            {
                return this.TopeField;
            }
            set
            {
                this.TopeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Intermediario", Namespace="http://schemas.datacontract.org/2004/07/TablasParametrizacionPersonas.Entidades")]
    public partial class Intermediario : object
    {
        
        private int CodigoAgenteField;
        
        private int CodigoEstadoField;
        
        private int CodigoTipoAgenteField;
        
        private int CodigoTipoDocumentoField;
        
        private string CorreoElectronicoField;
        
        private int DigitoVerificacionField;
        
        private string FechaBajaField;
        
        private int IdPersonaField;
        
        private string NombreEstadoField;
        
        private string NombreTipoAgenteField;
        
        private string NumeroDocumentoField;
        
        private string PrimerApellidoField;
        
        private string PrimerNombreField;
        
        private string SegundoApellidoField;
        
        private string SegundoNombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoAgente
        {
            get
            {
                return this.CodigoAgenteField;
            }
            set
            {
                this.CodigoAgenteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoEstado
        {
            get
            {
                return this.CodigoEstadoField;
            }
            set
            {
                this.CodigoEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoTipoAgente
        {
            get
            {
                return this.CodigoTipoAgenteField;
            }
            set
            {
                this.CodigoTipoAgenteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoTipoDocumento
        {
            get
            {
                return this.CodigoTipoDocumentoField;
            }
            set
            {
                this.CodigoTipoDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico
        {
            get
            {
                return this.CorreoElectronicoField;
            }
            set
            {
                this.CorreoElectronicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DigitoVerificacion
        {
            get
            {
                return this.DigitoVerificacionField;
            }
            set
            {
                this.DigitoVerificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaBaja
        {
            get
            {
                return this.FechaBajaField;
            }
            set
            {
                this.FechaBajaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPersona
        {
            get
            {
                return this.IdPersonaField;
            }
            set
            {
                this.IdPersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEstado
        {
            get
            {
                return this.NombreEstadoField;
            }
            set
            {
                this.NombreEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreTipoAgente
        {
            get
            {
                return this.NombreTipoAgenteField;
            }
            set
            {
                this.NombreTipoAgenteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumento
        {
            get
            {
                return this.NumeroDocumentoField;
            }
            set
            {
                this.NumeroDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerApellido
        {
            get
            {
                return this.PrimerApellidoField;
            }
            set
            {
                this.PrimerApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerNombre
        {
            get
            {
                return this.PrimerNombreField;
            }
            set
            {
                this.PrimerNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoApellido
        {
            get
            {
                return this.SegundoApellidoField;
            }
            set
            {
                this.SegundoApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoNombre
        {
            get
            {
                return this.SegundoNombreField;
            }
            set
            {
                this.SegundoNombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GastosCompannia", Namespace="http://schemas.datacontract.org/2004/07/TablasParametrizacionPersonas.Entidades")]
    public partial class GastosCompannia : object
    {
        
        private int AnnoField;
        
        private int CodigoRamoField;
        
        private decimal PorcentajeGastosField;
        
        private decimal PorcentajeIvaComisionField;
        
        private decimal PorcentajeIvaRetornoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Anno
        {
            get
            {
                return this.AnnoField;
            }
            set
            {
                this.AnnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoRamo
        {
            get
            {
                return this.CodigoRamoField;
            }
            set
            {
                this.CodigoRamoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PorcentajeGastos
        {
            get
            {
                return this.PorcentajeGastosField;
            }
            set
            {
                this.PorcentajeGastosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PorcentajeIvaComision
        {
            get
            {
                return this.PorcentajeIvaComisionField;
            }
            set
            {
                this.PorcentajeIvaComisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PorcentajeIvaRetorno
        {
            get
            {
                return this.PorcentajeIvaRetornoField;
            }
            set
            {
                this.PorcentajeIvaRetornoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UtilidadCompannia", Namespace="http://schemas.datacontract.org/2004/07/TablasParametrizacionPersonas.Entidades")]
    public partial class UtilidadCompannia : object
    {
        
        private int AnnoField;
        
        private int BaseField;
        
        private int CodigoRamoField;
        
        private int TopeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Anno
        {
            get
            {
                return this.AnnoField;
            }
            set
            {
                this.AnnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Base
        {
            get
            {
                return this.BaseField;
            }
            set
            {
                this.BaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoRamo
        {
            get
            {
                return this.CodigoRamoField;
            }
            set
            {
                this.CodigoRamoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tope
        {
            get
            {
                return this.TopeField;
            }
            set
            {
                this.TopeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerfilxEdad", Namespace="http://schemas.datacontract.org/2004/07/TablasParametrizacionPersonas.Entidades")]
    public partial class PerfilxEdad : object
    {
        
        private int CodigoPerfilField;
        
        private string NombrePerfilField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoPerfil
        {
            get
            {
                return this.CodigoPerfilField;
            }
            set
            {
                this.CodigoPerfilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombrePerfil
        {
            get
            {
                return this.NombrePerfilField;
            }
            set
            {
                this.NombrePerfilField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerfilxValor", Namespace="http://schemas.datacontract.org/2004/07/TablasParametrizacionPersonas.Entidades")]
    public partial class PerfilxValor : object
    {
        
        private int CodigoPerfilField;
        
        private string NombrePerfilField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoPerfil
        {
            get
            {
                return this.CodigoPerfilField;
            }
            set
            {
                this.CodigoPerfilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombrePerfil
        {
            get
            {
                return this.NombrePerfilField;
            }
            set
            {
                this.NombrePerfilField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RangoEdad", Namespace="http://schemas.datacontract.org/2004/07/TablasParametrizacionPersonas.Entidades")]
    public partial class RangoEdad : object
    {
        
        private int CodigoPerfilField;
        
        private int EdadDesdeField;
        
        private int EdadHastaField;
        
        private int OrdenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoPerfil
        {
            get
            {
                return this.CodigoPerfilField;
            }
            set
            {
                this.CodigoPerfilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EdadDesde
        {
            get
            {
                return this.EdadDesdeField;
            }
            set
            {
                this.EdadDesdeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EdadHasta
        {
            get
            {
                return this.EdadHastaField;
            }
            set
            {
                this.EdadHastaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Orden
        {
            get
            {
                return this.OrdenField;
            }
            set
            {
                this.OrdenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RangoValor", Namespace="http://schemas.datacontract.org/2004/07/TablasParametrizacionPersonas.Entidades")]
    public partial class RangoValor : object
    {
        
        private int CodigoPerfilField;
        
        private int OrdenField;
        
        private decimal ValorDesdeField;
        
        private decimal ValorHastaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoPerfil
        {
            get
            {
                return this.CodigoPerfilField;
            }
            set
            {
                this.CodigoPerfilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Orden
        {
            get
            {
                return this.OrdenField;
            }
            set
            {
                this.OrdenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorDesde
        {
            get
            {
                return this.ValorDesdeField;
            }
            set
            {
                this.ValorDesdeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorHasta
        {
            get
            {
                return this.ValorHastaField;
            }
            set
            {
                this.ValorHastaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sucursal", Namespace="http://schemas.datacontract.org/2004/07/TablasParametrizacionPersonas.Entidades")]
    public partial class Sucursal : object
    {
        
        private int CodigoSucursalField;
        
        private int CodigoZonaField;
        
        private string DireccionField;
        
        private string NombreSucursalField;
        
        private string NombreZonaField;
        
        private string TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoSucursal
        {
            get
            {
                return this.CodigoSucursalField;
            }
            set
            {
                this.CodigoSucursalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoZona
        {
            get
            {
                return this.CodigoZonaField;
            }
            set
            {
                this.CodigoZonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreSucursal
        {
            get
            {
                return this.NombreSucursalField;
            }
            set
            {
                this.NombreSucursalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreZona
        {
            get
            {
                return this.NombreZonaField;
            }
            set
            {
                this.NombreZonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zona", Namespace="http://schemas.datacontract.org/2004/07/TablasParametrizacionPersonas.Entidades")]
    public partial class Zona : object
    {
        
        private int CodigoGrupoField;
        
        private int CodigoZonaField;
        
        private string NombreZonaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoGrupo
        {
            get
            {
                return this.CodigoGrupoField;
            }
            set
            {
                this.CodigoGrupoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoZona
        {
            get
            {
                return this.CodigoZonaField;
            }
            set
            {
                this.CodigoZonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreZona
        {
            get
            {
                return this.NombreZonaField;
            }
            set
            {
                this.NombreZonaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rechazo", Namespace="http://schemas.datacontract.org/2004/07/TablasParametrizacionPersonas.Entidades")]
    public partial class Rechazo : object
    {
        
        private int CodigoRechazoField;
        
        private string NombreRechazoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoRechazo
        {
            get
            {
                return this.CodigoRechazoField;
            }
            set
            {
                this.CodigoRechazoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreRechazo
        {
            get
            {
                return this.NombreRechazoField;
            }
            set
            {
                this.NombreRechazoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PersonasServiceReference.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerRamos", ReplyAction="http://tempuri.org/IService1/TraerRamosResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.Ramo[]> TraerRamosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerRamo", ReplyAction="http://tempuri.org/IService1/TraerRamoResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.Ramo> TraerRamoAsync(int CodigoRamo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerSubRamosxRamo", ReplyAction="http://tempuri.org/IService1/TraerSubRamosxRamoResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.SubRamo[]> TraerSubRamosxRamoAsync(int CodigoRamo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerSubRamo", ReplyAction="http://tempuri.org/IService1/TraerSubRamoResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.SubRamo> TraerSubRamoAsync(int CodigoRamo, int CodigoSubRamo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerSectores", ReplyAction="http://tempuri.org/IService1/TraerSectoresResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.Sector[]> TraerSectoresAsync(int CodigoRamo, int CodigoSubramo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerSector", ReplyAction="http://tempuri.org/IService1/TraerSectorResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.Sector> TraerSectorAsync(int CodigoRamo, int CodigoSubramo, int CodigoSector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerTasas", ReplyAction="http://tempuri.org/IService1/TraerTasasResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.Tasa[]> TraerTasasAsync(int CodigoRamo, int CodigoSubramo, int CodigoSector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerTasa", ReplyAction="http://tempuri.org/IService1/TraerTasaResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.Tasa> TraerTasaAsync(int CodigoRamo, int CodigoSubramo, int CodigoSector, int CodigoTasa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerRiesgoActividades", ReplyAction="http://tempuri.org/IService1/TraerRiesgoActividadesResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.RiesgoActividad[]> TraerRiesgoActividadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerRiesgoActividad", ReplyAction="http://tempuri.org/IService1/TraerRiesgoActividadResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.RiesgoActividad> TraerRiesgoActividadAsync(int CodigoRiesgoActividad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerTipoNegocio", ReplyAction="http://tempuri.org/IService1/TraerTipoNegocioResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.TipoNegocio[]> TraerTipoNegocioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerTipoNegocioxCodigo", ReplyAction="http://tempuri.org/IService1/TraerTipoNegocioxCodigoResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.TipoNegocio> TraerTipoNegocioxCodigoAsync(int CodigoTipoNegocio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerTipoContratacion", ReplyAction="http://tempuri.org/IService1/TraerTipoContratacionResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.TipoContratacion[]> TraerTipoContratacionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerTipoContratacionxNegocio", ReplyAction="http://tempuri.org/IService1/TraerTipoContratacionxNegocioResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.TipoContratacion[]> TraerTipoContratacionxNegocioAsync(int CodigoTipoNegocio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerTipoContratacionxCodigo", ReplyAction="http://tempuri.org/IService1/TraerTipoContratacionxCodigoResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.TipoContratacion> TraerTipoContratacionxCodigoAsync(int CodigoTipoContratacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerTipoSumaAsegurada", ReplyAction="http://tempuri.org/IService1/TraerTipoSumaAseguradaResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.TipoSumaAsegurada[]> TraerTipoSumaAseguradaAsync(int CodigoRamo, int CodigoSubRamo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerTipoDocumento", ReplyAction="http://tempuri.org/IService1/TraerTipoDocumentoResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.TipoDocumento[]> TraerTipoDocumentoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerAmparos", ReplyAction="http://tempuri.org/IService1/TraerAmparosResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.Amparo[]> TraerAmparosAsync(int CodigoRamo, int CodigoSubRamo, int CodigoSector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerAmparosxRamo", ReplyAction="http://tempuri.org/IService1/TraerAmparosxRamoResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.Amparo[]> TraerAmparosxRamoAsync(int CodigoRamo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerAmparoxCodigo", ReplyAction="http://tempuri.org/IService1/TraerAmparoxCodigoResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.Amparo> TraerAmparoxCodigoAsync(int CodigoRamo, int CodigoSubRamo, int CodigoAmparo, int CodigoSector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerIntermediarioxCodigo", ReplyAction="http://tempuri.org/IService1/TraerIntermediarioxCodigoResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.Intermediario> TraerIntermediarioxCodigoAsync(int CodigoSucursal, int Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerIntermediarioxDocumento", ReplyAction="http://tempuri.org/IService1/TraerIntermediarioxDocumentoResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.Intermediario> TraerIntermediarioxDocumentoAsync(int CodigoSucursal, int CodigoTipoDocumento, string NumeroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerIntermediariosxSucursal", ReplyAction="http://tempuri.org/IService1/TraerIntermediariosxSucursalResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.Intermediario[]> TraerIntermediariosxSucursalAsync(int CodigoSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerIntermediarioxClave", ReplyAction="http://tempuri.org/IService1/TraerIntermediarioxClaveResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.Intermediario> TraerIntermediarioxClaveAsync(int Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerGastosCompannia", ReplyAction="http://tempuri.org/IService1/TraerGastosCompanniaResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.GastosCompannia> TraerGastosCompanniaAsync(int CodigoRamo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerUtilidadCompannia", ReplyAction="http://tempuri.org/IService1/TraerUtilidadCompanniaResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.UtilidadCompannia> TraerUtilidadCompanniaAsync(int CodigoRamo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerPerfilesxEdad", ReplyAction="http://tempuri.org/IService1/TraerPerfilesxEdadResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.PerfilxEdad[]> TraerPerfilesxEdadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerPerfilesxValor", ReplyAction="http://tempuri.org/IService1/TraerPerfilesxValorResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.PerfilxValor[]> TraerPerfilesxValorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerRangosxPerfilEdad", ReplyAction="http://tempuri.org/IService1/TraerRangosxPerfilEdadResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.RangoEdad[]> TraerRangosxPerfilEdadAsync(int CodigoPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerRangosxPerfilValor", ReplyAction="http://tempuri.org/IService1/TraerRangosxPerfilValorResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.RangoValor[]> TraerRangosxPerfilValorAsync(int CodigoPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerSucursales", ReplyAction="http://tempuri.org/IService1/TraerSucursalesResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.Sucursal[]> TraerSucursalesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerSucursalxCodigo", ReplyAction="http://tempuri.org/IService1/TraerSucursalxCodigoResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.Sucursal> TraerSucursalxCodigoAsync(int CodigoSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerSucursalesxZona", ReplyAction="http://tempuri.org/IService1/TraerSucursalesxZonaResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.Sucursal[]> TraerSucursalesxZonaAsync(int CodigoZona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerSucursalesxIntermediario", ReplyAction="http://tempuri.org/IService1/TraerSucursalesxIntermediarioResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.Sucursal[]> TraerSucursalesxIntermediarioAsync(int Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerZonas", ReplyAction="http://tempuri.org/IService1/TraerZonasResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.Zona[]> TraerZonasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerZonaxCodigo", ReplyAction="http://tempuri.org/IService1/TraerZonaxCodigoResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.Zona> TraerZonaxCodigoAsync(int CodigoZona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerTasaSiniestralidad", ReplyAction="http://tempuri.org/IService1/TraerTasaSiniestralidadResponse")]
        System.Threading.Tasks.Task<decimal> TraerTasaSiniestralidadAsync(int CodigoRamo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerRechazos", ReplyAction="http://tempuri.org/IService1/TraerRechazosResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.Rechazo[]> TraerRechazosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerRechazo", ReplyAction="http://tempuri.org/IService1/TraerRechazoResponse")]
        System.Threading.Tasks.Task<PersonasServiceReference.Rechazo> TraerRechazoAsync(int CodigoRechazo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IService1Channel : PersonasServiceReference.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PersonasServiceReference.IService1>, PersonasServiceReference.IService1
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.Ramo[]> TraerRamosAsync()
        {
            return base.Channel.TraerRamosAsync();
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.Ramo> TraerRamoAsync(int CodigoRamo)
        {
            return base.Channel.TraerRamoAsync(CodigoRamo);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.SubRamo[]> TraerSubRamosxRamoAsync(int CodigoRamo)
        {
            return base.Channel.TraerSubRamosxRamoAsync(CodigoRamo);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.SubRamo> TraerSubRamoAsync(int CodigoRamo, int CodigoSubRamo)
        {
            return base.Channel.TraerSubRamoAsync(CodigoRamo, CodigoSubRamo);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.Sector[]> TraerSectoresAsync(int CodigoRamo, int CodigoSubramo)
        {
            return base.Channel.TraerSectoresAsync(CodigoRamo, CodigoSubramo);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.Sector> TraerSectorAsync(int CodigoRamo, int CodigoSubramo, int CodigoSector)
        {
            return base.Channel.TraerSectorAsync(CodigoRamo, CodigoSubramo, CodigoSector);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.Tasa[]> TraerTasasAsync(int CodigoRamo, int CodigoSubramo, int CodigoSector)
        {
            return base.Channel.TraerTasasAsync(CodigoRamo, CodigoSubramo, CodigoSector);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.Tasa> TraerTasaAsync(int CodigoRamo, int CodigoSubramo, int CodigoSector, int CodigoTasa)
        {
            return base.Channel.TraerTasaAsync(CodigoRamo, CodigoSubramo, CodigoSector, CodigoTasa);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.RiesgoActividad[]> TraerRiesgoActividadesAsync()
        {
            return base.Channel.TraerRiesgoActividadesAsync();
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.RiesgoActividad> TraerRiesgoActividadAsync(int CodigoRiesgoActividad)
        {
            return base.Channel.TraerRiesgoActividadAsync(CodigoRiesgoActividad);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.TipoNegocio[]> TraerTipoNegocioAsync()
        {
            return base.Channel.TraerTipoNegocioAsync();
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.TipoNegocio> TraerTipoNegocioxCodigoAsync(int CodigoTipoNegocio)
        {
            return base.Channel.TraerTipoNegocioxCodigoAsync(CodigoTipoNegocio);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.TipoContratacion[]> TraerTipoContratacionAsync()
        {
            return base.Channel.TraerTipoContratacionAsync();
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.TipoContratacion[]> TraerTipoContratacionxNegocioAsync(int CodigoTipoNegocio)
        {
            return base.Channel.TraerTipoContratacionxNegocioAsync(CodigoTipoNegocio);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.TipoContratacion> TraerTipoContratacionxCodigoAsync(int CodigoTipoContratacion)
        {
            return base.Channel.TraerTipoContratacionxCodigoAsync(CodigoTipoContratacion);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.TipoSumaAsegurada[]> TraerTipoSumaAseguradaAsync(int CodigoRamo, int CodigoSubRamo)
        {
            return base.Channel.TraerTipoSumaAseguradaAsync(CodigoRamo, CodigoSubRamo);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.TipoDocumento[]> TraerTipoDocumentoAsync()
        {
            return base.Channel.TraerTipoDocumentoAsync();
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.Amparo[]> TraerAmparosAsync(int CodigoRamo, int CodigoSubRamo, int CodigoSector)
        {
            return base.Channel.TraerAmparosAsync(CodigoRamo, CodigoSubRamo, CodigoSector);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.Amparo[]> TraerAmparosxRamoAsync(int CodigoRamo)
        {
            return base.Channel.TraerAmparosxRamoAsync(CodigoRamo);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.Amparo> TraerAmparoxCodigoAsync(int CodigoRamo, int CodigoSubRamo, int CodigoAmparo, int CodigoSector)
        {
            return base.Channel.TraerAmparoxCodigoAsync(CodigoRamo, CodigoSubRamo, CodigoAmparo, CodigoSector);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.Intermediario> TraerIntermediarioxCodigoAsync(int CodigoSucursal, int Clave)
        {
            return base.Channel.TraerIntermediarioxCodigoAsync(CodigoSucursal, Clave);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.Intermediario> TraerIntermediarioxDocumentoAsync(int CodigoSucursal, int CodigoTipoDocumento, string NumeroDocumento)
        {
            return base.Channel.TraerIntermediarioxDocumentoAsync(CodigoSucursal, CodigoTipoDocumento, NumeroDocumento);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.Intermediario[]> TraerIntermediariosxSucursalAsync(int CodigoSucursal)
        {
            return base.Channel.TraerIntermediariosxSucursalAsync(CodigoSucursal);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.Intermediario> TraerIntermediarioxClaveAsync(int Clave)
        {
            return base.Channel.TraerIntermediarioxClaveAsync(Clave);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.GastosCompannia> TraerGastosCompanniaAsync(int CodigoRamo)
        {
            return base.Channel.TraerGastosCompanniaAsync(CodigoRamo);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.UtilidadCompannia> TraerUtilidadCompanniaAsync(int CodigoRamo)
        {
            return base.Channel.TraerUtilidadCompanniaAsync(CodigoRamo);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.PerfilxEdad[]> TraerPerfilesxEdadAsync()
        {
            return base.Channel.TraerPerfilesxEdadAsync();
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.PerfilxValor[]> TraerPerfilesxValorAsync()
        {
            return base.Channel.TraerPerfilesxValorAsync();
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.RangoEdad[]> TraerRangosxPerfilEdadAsync(int CodigoPerfil)
        {
            return base.Channel.TraerRangosxPerfilEdadAsync(CodigoPerfil);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.RangoValor[]> TraerRangosxPerfilValorAsync(int CodigoPerfil)
        {
            return base.Channel.TraerRangosxPerfilValorAsync(CodigoPerfil);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.Sucursal[]> TraerSucursalesAsync()
        {
            return base.Channel.TraerSucursalesAsync();
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.Sucursal> TraerSucursalxCodigoAsync(int CodigoSucursal)
        {
            return base.Channel.TraerSucursalxCodigoAsync(CodigoSucursal);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.Sucursal[]> TraerSucursalesxZonaAsync(int CodigoZona)
        {
            return base.Channel.TraerSucursalesxZonaAsync(CodigoZona);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.Sucursal[]> TraerSucursalesxIntermediarioAsync(int Clave)
        {
            return base.Channel.TraerSucursalesxIntermediarioAsync(Clave);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.Zona[]> TraerZonasAsync()
        {
            return base.Channel.TraerZonasAsync();
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.Zona> TraerZonaxCodigoAsync(int CodigoZona)
        {
            return base.Channel.TraerZonaxCodigoAsync(CodigoZona);
        }
        
        public System.Threading.Tasks.Task<decimal> TraerTasaSiniestralidadAsync(int CodigoRamo)
        {
            return base.Channel.TraerTasaSiniestralidadAsync(CodigoRamo);
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.Rechazo[]> TraerRechazosAsync()
        {
            return base.Channel.TraerRechazosAsync();
        }
        
        public System.Threading.Tasks.Task<PersonasServiceReference.Rechazo> TraerRechazoAsync(int CodigoRechazo)
        {
            return base.Channel.TraerRechazoAsync(CodigoRechazo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://192.1.3.183:8082/WCFTablasParametrizacionPersonas/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
